// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package user

//go:generate minimock -i github.com/meetmorrowsolonmars/education-pet-project/internal/domain/user.AccountStore -o account_store_mock_test.go -n AccountStoreMock -p user

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/meetmorrowsolonmars/education-pet-project/internal/domain/model"
)

// AccountStoreMock implements AccountStore
type AccountStoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateDefault          func(ctx context.Context, userID int64) (a1 model.Account, err error)
	funcCreateDefaultOrigin    string
	inspectFuncCreateDefault   func(ctx context.Context, userID int64)
	afterCreateDefaultCounter  uint64
	beforeCreateDefaultCounter uint64
	CreateDefaultMock          mAccountStoreMockCreateDefault
}

// NewAccountStoreMock returns a mock for AccountStore
func NewAccountStoreMock(t minimock.Tester) *AccountStoreMock {
	m := &AccountStoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateDefaultMock = mAccountStoreMockCreateDefault{mock: m}
	m.CreateDefaultMock.callArgs = []*AccountStoreMockCreateDefaultParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAccountStoreMockCreateDefault struct {
	optional           bool
	mock               *AccountStoreMock
	defaultExpectation *AccountStoreMockCreateDefaultExpectation
	expectations       []*AccountStoreMockCreateDefaultExpectation

	callArgs []*AccountStoreMockCreateDefaultParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccountStoreMockCreateDefaultExpectation specifies expectation struct of the AccountStore.CreateDefault
type AccountStoreMockCreateDefaultExpectation struct {
	mock               *AccountStoreMock
	params             *AccountStoreMockCreateDefaultParams
	paramPtrs          *AccountStoreMockCreateDefaultParamPtrs
	expectationOrigins AccountStoreMockCreateDefaultExpectationOrigins
	results            *AccountStoreMockCreateDefaultResults
	returnOrigin       string
	Counter            uint64
}

// AccountStoreMockCreateDefaultParams contains parameters of the AccountStore.CreateDefault
type AccountStoreMockCreateDefaultParams struct {
	ctx    context.Context
	userID int64
}

// AccountStoreMockCreateDefaultParamPtrs contains pointers to parameters of the AccountStore.CreateDefault
type AccountStoreMockCreateDefaultParamPtrs struct {
	ctx    *context.Context
	userID *int64
}

// AccountStoreMockCreateDefaultResults contains results of the AccountStore.CreateDefault
type AccountStoreMockCreateDefaultResults struct {
	a1  model.Account
	err error
}

// AccountStoreMockCreateDefaultOrigins contains origins of expectations of the AccountStore.CreateDefault
type AccountStoreMockCreateDefaultExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateDefault *mAccountStoreMockCreateDefault) Optional() *mAccountStoreMockCreateDefault {
	mmCreateDefault.optional = true
	return mmCreateDefault
}

// Expect sets up expected params for AccountStore.CreateDefault
func (mmCreateDefault *mAccountStoreMockCreateDefault) Expect(ctx context.Context, userID int64) *mAccountStoreMockCreateDefault {
	if mmCreateDefault.mock.funcCreateDefault != nil {
		mmCreateDefault.mock.t.Fatalf("AccountStoreMock.CreateDefault mock is already set by Set")
	}

	if mmCreateDefault.defaultExpectation == nil {
		mmCreateDefault.defaultExpectation = &AccountStoreMockCreateDefaultExpectation{}
	}

	if mmCreateDefault.defaultExpectation.paramPtrs != nil {
		mmCreateDefault.mock.t.Fatalf("AccountStoreMock.CreateDefault mock is already set by ExpectParams functions")
	}

	mmCreateDefault.defaultExpectation.params = &AccountStoreMockCreateDefaultParams{ctx, userID}
	mmCreateDefault.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateDefault.expectations {
		if minimock.Equal(e.params, mmCreateDefault.defaultExpectation.params) {
			mmCreateDefault.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateDefault.defaultExpectation.params)
		}
	}

	return mmCreateDefault
}

// ExpectCtxParam1 sets up expected param ctx for AccountStore.CreateDefault
func (mmCreateDefault *mAccountStoreMockCreateDefault) ExpectCtxParam1(ctx context.Context) *mAccountStoreMockCreateDefault {
	if mmCreateDefault.mock.funcCreateDefault != nil {
		mmCreateDefault.mock.t.Fatalf("AccountStoreMock.CreateDefault mock is already set by Set")
	}

	if mmCreateDefault.defaultExpectation == nil {
		mmCreateDefault.defaultExpectation = &AccountStoreMockCreateDefaultExpectation{}
	}

	if mmCreateDefault.defaultExpectation.params != nil {
		mmCreateDefault.mock.t.Fatalf("AccountStoreMock.CreateDefault mock is already set by Expect")
	}

	if mmCreateDefault.defaultExpectation.paramPtrs == nil {
		mmCreateDefault.defaultExpectation.paramPtrs = &AccountStoreMockCreateDefaultParamPtrs{}
	}
	mmCreateDefault.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateDefault.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateDefault
}

// ExpectUserIDParam2 sets up expected param userID for AccountStore.CreateDefault
func (mmCreateDefault *mAccountStoreMockCreateDefault) ExpectUserIDParam2(userID int64) *mAccountStoreMockCreateDefault {
	if mmCreateDefault.mock.funcCreateDefault != nil {
		mmCreateDefault.mock.t.Fatalf("AccountStoreMock.CreateDefault mock is already set by Set")
	}

	if mmCreateDefault.defaultExpectation == nil {
		mmCreateDefault.defaultExpectation = &AccountStoreMockCreateDefaultExpectation{}
	}

	if mmCreateDefault.defaultExpectation.params != nil {
		mmCreateDefault.mock.t.Fatalf("AccountStoreMock.CreateDefault mock is already set by Expect")
	}

	if mmCreateDefault.defaultExpectation.paramPtrs == nil {
		mmCreateDefault.defaultExpectation.paramPtrs = &AccountStoreMockCreateDefaultParamPtrs{}
	}
	mmCreateDefault.defaultExpectation.paramPtrs.userID = &userID
	mmCreateDefault.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmCreateDefault
}

// Inspect accepts an inspector function that has same arguments as the AccountStore.CreateDefault
func (mmCreateDefault *mAccountStoreMockCreateDefault) Inspect(f func(ctx context.Context, userID int64)) *mAccountStoreMockCreateDefault {
	if mmCreateDefault.mock.inspectFuncCreateDefault != nil {
		mmCreateDefault.mock.t.Fatalf("Inspect function is already set for AccountStoreMock.CreateDefault")
	}

	mmCreateDefault.mock.inspectFuncCreateDefault = f

	return mmCreateDefault
}

// Return sets up results that will be returned by AccountStore.CreateDefault
func (mmCreateDefault *mAccountStoreMockCreateDefault) Return(a1 model.Account, err error) *AccountStoreMock {
	if mmCreateDefault.mock.funcCreateDefault != nil {
		mmCreateDefault.mock.t.Fatalf("AccountStoreMock.CreateDefault mock is already set by Set")
	}

	if mmCreateDefault.defaultExpectation == nil {
		mmCreateDefault.defaultExpectation = &AccountStoreMockCreateDefaultExpectation{mock: mmCreateDefault.mock}
	}
	mmCreateDefault.defaultExpectation.results = &AccountStoreMockCreateDefaultResults{a1, err}
	mmCreateDefault.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateDefault.mock
}

// Set uses given function f to mock the AccountStore.CreateDefault method
func (mmCreateDefault *mAccountStoreMockCreateDefault) Set(f func(ctx context.Context, userID int64) (a1 model.Account, err error)) *AccountStoreMock {
	if mmCreateDefault.defaultExpectation != nil {
		mmCreateDefault.mock.t.Fatalf("Default expectation is already set for the AccountStore.CreateDefault method")
	}

	if len(mmCreateDefault.expectations) > 0 {
		mmCreateDefault.mock.t.Fatalf("Some expectations are already set for the AccountStore.CreateDefault method")
	}

	mmCreateDefault.mock.funcCreateDefault = f
	mmCreateDefault.mock.funcCreateDefaultOrigin = minimock.CallerInfo(1)
	return mmCreateDefault.mock
}

// When sets expectation for the AccountStore.CreateDefault which will trigger the result defined by the following
// Then helper
func (mmCreateDefault *mAccountStoreMockCreateDefault) When(ctx context.Context, userID int64) *AccountStoreMockCreateDefaultExpectation {
	if mmCreateDefault.mock.funcCreateDefault != nil {
		mmCreateDefault.mock.t.Fatalf("AccountStoreMock.CreateDefault mock is already set by Set")
	}

	expectation := &AccountStoreMockCreateDefaultExpectation{
		mock:               mmCreateDefault.mock,
		params:             &AccountStoreMockCreateDefaultParams{ctx, userID},
		expectationOrigins: AccountStoreMockCreateDefaultExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateDefault.expectations = append(mmCreateDefault.expectations, expectation)
	return expectation
}

// Then sets up AccountStore.CreateDefault return parameters for the expectation previously defined by the When method
func (e *AccountStoreMockCreateDefaultExpectation) Then(a1 model.Account, err error) *AccountStoreMock {
	e.results = &AccountStoreMockCreateDefaultResults{a1, err}
	return e.mock
}

// Times sets number of times AccountStore.CreateDefault should be invoked
func (mmCreateDefault *mAccountStoreMockCreateDefault) Times(n uint64) *mAccountStoreMockCreateDefault {
	if n == 0 {
		mmCreateDefault.mock.t.Fatalf("Times of AccountStoreMock.CreateDefault mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateDefault.expectedInvocations, n)
	mmCreateDefault.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateDefault
}

func (mmCreateDefault *mAccountStoreMockCreateDefault) invocationsDone() bool {
	if len(mmCreateDefault.expectations) == 0 && mmCreateDefault.defaultExpectation == nil && mmCreateDefault.mock.funcCreateDefault == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateDefault.mock.afterCreateDefaultCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateDefault.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateDefault implements AccountStore
func (mmCreateDefault *AccountStoreMock) CreateDefault(ctx context.Context, userID int64) (a1 model.Account, err error) {
	mm_atomic.AddUint64(&mmCreateDefault.beforeCreateDefaultCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateDefault.afterCreateDefaultCounter, 1)

	mmCreateDefault.t.Helper()

	if mmCreateDefault.inspectFuncCreateDefault != nil {
		mmCreateDefault.inspectFuncCreateDefault(ctx, userID)
	}

	mm_params := AccountStoreMockCreateDefaultParams{ctx, userID}

	// Record call args
	mmCreateDefault.CreateDefaultMock.mutex.Lock()
	mmCreateDefault.CreateDefaultMock.callArgs = append(mmCreateDefault.CreateDefaultMock.callArgs, &mm_params)
	mmCreateDefault.CreateDefaultMock.mutex.Unlock()

	for _, e := range mmCreateDefault.CreateDefaultMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.a1, e.results.err
		}
	}

	if mmCreateDefault.CreateDefaultMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateDefault.CreateDefaultMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateDefault.CreateDefaultMock.defaultExpectation.params
		mm_want_ptrs := mmCreateDefault.CreateDefaultMock.defaultExpectation.paramPtrs

		mm_got := AccountStoreMockCreateDefaultParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateDefault.t.Errorf("AccountStoreMock.CreateDefault got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateDefault.CreateDefaultMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmCreateDefault.t.Errorf("AccountStoreMock.CreateDefault got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateDefault.CreateDefaultMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateDefault.t.Errorf("AccountStoreMock.CreateDefault got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateDefault.CreateDefaultMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateDefault.CreateDefaultMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateDefault.t.Fatal("No results are set for the AccountStoreMock.CreateDefault")
		}
		return (*mm_results).a1, (*mm_results).err
	}
	if mmCreateDefault.funcCreateDefault != nil {
		return mmCreateDefault.funcCreateDefault(ctx, userID)
	}
	mmCreateDefault.t.Fatalf("Unexpected call to AccountStoreMock.CreateDefault. %v %v", ctx, userID)
	return
}

// CreateDefaultAfterCounter returns a count of finished AccountStoreMock.CreateDefault invocations
func (mmCreateDefault *AccountStoreMock) CreateDefaultAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateDefault.afterCreateDefaultCounter)
}

// CreateDefaultBeforeCounter returns a count of AccountStoreMock.CreateDefault invocations
func (mmCreateDefault *AccountStoreMock) CreateDefaultBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateDefault.beforeCreateDefaultCounter)
}

// Calls returns a list of arguments used in each call to AccountStoreMock.CreateDefault.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateDefault *mAccountStoreMockCreateDefault) Calls() []*AccountStoreMockCreateDefaultParams {
	mmCreateDefault.mutex.RLock()

	argCopy := make([]*AccountStoreMockCreateDefaultParams, len(mmCreateDefault.callArgs))
	copy(argCopy, mmCreateDefault.callArgs)

	mmCreateDefault.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDefaultDone returns true if the count of the CreateDefault invocations corresponds
// the number of defined expectations
func (m *AccountStoreMock) MinimockCreateDefaultDone() bool {
	if m.CreateDefaultMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateDefaultMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateDefaultMock.invocationsDone()
}

// MinimockCreateDefaultInspect logs each unmet expectation
func (m *AccountStoreMock) MinimockCreateDefaultInspect() {
	for _, e := range m.CreateDefaultMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccountStoreMock.CreateDefault at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateDefaultCounter := mm_atomic.LoadUint64(&m.afterCreateDefaultCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateDefaultMock.defaultExpectation != nil && afterCreateDefaultCounter < 1 {
		if m.CreateDefaultMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccountStoreMock.CreateDefault at\n%s", m.CreateDefaultMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccountStoreMock.CreateDefault at\n%s with params: %#v", m.CreateDefaultMock.defaultExpectation.expectationOrigins.origin, *m.CreateDefaultMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateDefault != nil && afterCreateDefaultCounter < 1 {
		m.t.Errorf("Expected call to AccountStoreMock.CreateDefault at\n%s", m.funcCreateDefaultOrigin)
	}

	if !m.CreateDefaultMock.invocationsDone() && afterCreateDefaultCounter > 0 {
		m.t.Errorf("Expected %d calls to AccountStoreMock.CreateDefault at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateDefaultMock.expectedInvocations), m.CreateDefaultMock.expectedInvocationsOrigin, afterCreateDefaultCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AccountStoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateDefaultInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AccountStoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AccountStoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDefaultDone()
}
