// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package operation

//go:generate minimock -i github.com/meetmorrowsolonmars/education-pet-project/internal/api/v1/operation.OperationService -o operation_service_mock_test.go -n OperationServiceMock -p operation

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
	"github.com/meetmorrowsolonmars/education-pet-project/internal/domain/model"
	"github.com/shopspring/decimal"
)

// OperationServiceMock implements OperationService
type OperationServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, operation model.Operation) (o1 model.Operation, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, operation model.Operation)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mOperationServiceMockCreate

	funcDelete          func(ctx context.Context, id uuid.UUID) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, id uuid.UUID)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mOperationServiceMockDelete

	funcGetByAccountID          func(ctx context.Context, account int64, limit int64, offset int64) (oa1 []model.Operation, err error)
	funcGetByAccountIDOrigin    string
	inspectFuncGetByAccountID   func(ctx context.Context, account int64, limit int64, offset int64)
	afterGetByAccountIDCounter  uint64
	beforeGetByAccountIDCounter uint64
	GetByAccountIDMock          mOperationServiceMockGetByAccountID

	funcUpdate          func(ctx context.Context, id uuid.UUID, amount decimal.Decimal, categoryID int64, description string) (err error)
	funcUpdateOrigin    string
	inspectFuncUpdate   func(ctx context.Context, id uuid.UUID, amount decimal.Decimal, categoryID int64, description string)
	afterUpdateCounter  uint64
	beforeUpdateCounter uint64
	UpdateMock          mOperationServiceMockUpdate
}

// NewOperationServiceMock returns a mock for OperationService
func NewOperationServiceMock(t minimock.Tester) *OperationServiceMock {
	m := &OperationServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mOperationServiceMockCreate{mock: m}
	m.CreateMock.callArgs = []*OperationServiceMockCreateParams{}

	m.DeleteMock = mOperationServiceMockDelete{mock: m}
	m.DeleteMock.callArgs = []*OperationServiceMockDeleteParams{}

	m.GetByAccountIDMock = mOperationServiceMockGetByAccountID{mock: m}
	m.GetByAccountIDMock.callArgs = []*OperationServiceMockGetByAccountIDParams{}

	m.UpdateMock = mOperationServiceMockUpdate{mock: m}
	m.UpdateMock.callArgs = []*OperationServiceMockUpdateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOperationServiceMockCreate struct {
	optional           bool
	mock               *OperationServiceMock
	defaultExpectation *OperationServiceMockCreateExpectation
	expectations       []*OperationServiceMockCreateExpectation

	callArgs []*OperationServiceMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OperationServiceMockCreateExpectation specifies expectation struct of the OperationService.Create
type OperationServiceMockCreateExpectation struct {
	mock               *OperationServiceMock
	params             *OperationServiceMockCreateParams
	paramPtrs          *OperationServiceMockCreateParamPtrs
	expectationOrigins OperationServiceMockCreateExpectationOrigins
	results            *OperationServiceMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// OperationServiceMockCreateParams contains parameters of the OperationService.Create
type OperationServiceMockCreateParams struct {
	ctx       context.Context
	operation model.Operation
}

// OperationServiceMockCreateParamPtrs contains pointers to parameters of the OperationService.Create
type OperationServiceMockCreateParamPtrs struct {
	ctx       *context.Context
	operation *model.Operation
}

// OperationServiceMockCreateResults contains results of the OperationService.Create
type OperationServiceMockCreateResults struct {
	o1  model.Operation
	err error
}

// OperationServiceMockCreateOrigins contains origins of expectations of the OperationService.Create
type OperationServiceMockCreateExpectationOrigins struct {
	origin          string
	originCtx       string
	originOperation string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mOperationServiceMockCreate) Optional() *mOperationServiceMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for OperationService.Create
func (mmCreate *mOperationServiceMockCreate) Expect(ctx context.Context, operation model.Operation) *mOperationServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("OperationServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &OperationServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("OperationServiceMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &OperationServiceMockCreateParams{ctx, operation}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for OperationService.Create
func (mmCreate *mOperationServiceMockCreate) ExpectCtxParam1(ctx context.Context) *mOperationServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("OperationServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &OperationServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("OperationServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &OperationServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectOperationParam2 sets up expected param operation for OperationService.Create
func (mmCreate *mOperationServiceMockCreate) ExpectOperationParam2(operation model.Operation) *mOperationServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("OperationServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &OperationServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("OperationServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &OperationServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.operation = &operation
	mmCreate.defaultExpectation.expectationOrigins.originOperation = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the OperationService.Create
func (mmCreate *mOperationServiceMockCreate) Inspect(f func(ctx context.Context, operation model.Operation)) *mOperationServiceMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for OperationServiceMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by OperationService.Create
func (mmCreate *mOperationServiceMockCreate) Return(o1 model.Operation, err error) *OperationServiceMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("OperationServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &OperationServiceMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &OperationServiceMockCreateResults{o1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the OperationService.Create method
func (mmCreate *mOperationServiceMockCreate) Set(f func(ctx context.Context, operation model.Operation) (o1 model.Operation, err error)) *OperationServiceMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the OperationService.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the OperationService.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the OperationService.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mOperationServiceMockCreate) When(ctx context.Context, operation model.Operation) *OperationServiceMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("OperationServiceMock.Create mock is already set by Set")
	}

	expectation := &OperationServiceMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &OperationServiceMockCreateParams{ctx, operation},
		expectationOrigins: OperationServiceMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up OperationService.Create return parameters for the expectation previously defined by the When method
func (e *OperationServiceMockCreateExpectation) Then(o1 model.Operation, err error) *OperationServiceMock {
	e.results = &OperationServiceMockCreateResults{o1, err}
	return e.mock
}

// Times sets number of times OperationService.Create should be invoked
func (mmCreate *mOperationServiceMockCreate) Times(n uint64) *mOperationServiceMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of OperationServiceMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mOperationServiceMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements OperationService
func (mmCreate *OperationServiceMock) Create(ctx context.Context, operation model.Operation) (o1 model.Operation, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, operation)
	}

	mm_params := OperationServiceMockCreateParams{ctx, operation}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.o1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := OperationServiceMockCreateParams{ctx, operation}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("OperationServiceMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.operation != nil && !minimock.Equal(*mm_want_ptrs.operation, mm_got.operation) {
				mmCreate.t.Errorf("OperationServiceMock.Create got unexpected parameter operation, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originOperation, *mm_want_ptrs.operation, mm_got.operation, minimock.Diff(*mm_want_ptrs.operation, mm_got.operation))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("OperationServiceMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the OperationServiceMock.Create")
		}
		return (*mm_results).o1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, operation)
	}
	mmCreate.t.Fatalf("Unexpected call to OperationServiceMock.Create. %v %v", ctx, operation)
	return
}

// CreateAfterCounter returns a count of finished OperationServiceMock.Create invocations
func (mmCreate *OperationServiceMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of OperationServiceMock.Create invocations
func (mmCreate *OperationServiceMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to OperationServiceMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mOperationServiceMockCreate) Calls() []*OperationServiceMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*OperationServiceMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *OperationServiceMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *OperationServiceMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OperationServiceMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OperationServiceMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OperationServiceMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to OperationServiceMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to OperationServiceMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mOperationServiceMockDelete struct {
	optional           bool
	mock               *OperationServiceMock
	defaultExpectation *OperationServiceMockDeleteExpectation
	expectations       []*OperationServiceMockDeleteExpectation

	callArgs []*OperationServiceMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OperationServiceMockDeleteExpectation specifies expectation struct of the OperationService.Delete
type OperationServiceMockDeleteExpectation struct {
	mock               *OperationServiceMock
	params             *OperationServiceMockDeleteParams
	paramPtrs          *OperationServiceMockDeleteParamPtrs
	expectationOrigins OperationServiceMockDeleteExpectationOrigins
	results            *OperationServiceMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// OperationServiceMockDeleteParams contains parameters of the OperationService.Delete
type OperationServiceMockDeleteParams struct {
	ctx context.Context
	id  uuid.UUID
}

// OperationServiceMockDeleteParamPtrs contains pointers to parameters of the OperationService.Delete
type OperationServiceMockDeleteParamPtrs struct {
	ctx *context.Context
	id  *uuid.UUID
}

// OperationServiceMockDeleteResults contains results of the OperationService.Delete
type OperationServiceMockDeleteResults struct {
	err error
}

// OperationServiceMockDeleteOrigins contains origins of expectations of the OperationService.Delete
type OperationServiceMockDeleteExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mOperationServiceMockDelete) Optional() *mOperationServiceMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for OperationService.Delete
func (mmDelete *mOperationServiceMockDelete) Expect(ctx context.Context, id uuid.UUID) *mOperationServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("OperationServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &OperationServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("OperationServiceMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &OperationServiceMockDeleteParams{ctx, id}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for OperationService.Delete
func (mmDelete *mOperationServiceMockDelete) ExpectCtxParam1(ctx context.Context) *mOperationServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("OperationServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &OperationServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("OperationServiceMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &OperationServiceMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectIdParam2 sets up expected param id for OperationService.Delete
func (mmDelete *mOperationServiceMockDelete) ExpectIdParam2(id uuid.UUID) *mOperationServiceMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("OperationServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &OperationServiceMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("OperationServiceMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &OperationServiceMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.id = &id
	mmDelete.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the OperationService.Delete
func (mmDelete *mOperationServiceMockDelete) Inspect(f func(ctx context.Context, id uuid.UUID)) *mOperationServiceMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for OperationServiceMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by OperationService.Delete
func (mmDelete *mOperationServiceMockDelete) Return(err error) *OperationServiceMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("OperationServiceMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &OperationServiceMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &OperationServiceMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the OperationService.Delete method
func (mmDelete *mOperationServiceMockDelete) Set(f func(ctx context.Context, id uuid.UUID) (err error)) *OperationServiceMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the OperationService.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the OperationService.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the OperationService.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mOperationServiceMockDelete) When(ctx context.Context, id uuid.UUID) *OperationServiceMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("OperationServiceMock.Delete mock is already set by Set")
	}

	expectation := &OperationServiceMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &OperationServiceMockDeleteParams{ctx, id},
		expectationOrigins: OperationServiceMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up OperationService.Delete return parameters for the expectation previously defined by the When method
func (e *OperationServiceMockDeleteExpectation) Then(err error) *OperationServiceMock {
	e.results = &OperationServiceMockDeleteResults{err}
	return e.mock
}

// Times sets number of times OperationService.Delete should be invoked
func (mmDelete *mOperationServiceMockDelete) Times(n uint64) *mOperationServiceMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of OperationServiceMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mOperationServiceMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements OperationService
func (mmDelete *OperationServiceMock) Delete(ctx context.Context, id uuid.UUID) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, id)
	}

	mm_params := OperationServiceMockDeleteParams{ctx, id}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := OperationServiceMockDeleteParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("OperationServiceMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDelete.t.Errorf("OperationServiceMock.Delete got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("OperationServiceMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the OperationServiceMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, id)
	}
	mmDelete.t.Fatalf("Unexpected call to OperationServiceMock.Delete. %v %v", ctx, id)
	return
}

// DeleteAfterCounter returns a count of finished OperationServiceMock.Delete invocations
func (mmDelete *OperationServiceMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of OperationServiceMock.Delete invocations
func (mmDelete *OperationServiceMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to OperationServiceMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mOperationServiceMockDelete) Calls() []*OperationServiceMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*OperationServiceMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *OperationServiceMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *OperationServiceMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OperationServiceMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OperationServiceMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OperationServiceMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to OperationServiceMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to OperationServiceMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mOperationServiceMockGetByAccountID struct {
	optional           bool
	mock               *OperationServiceMock
	defaultExpectation *OperationServiceMockGetByAccountIDExpectation
	expectations       []*OperationServiceMockGetByAccountIDExpectation

	callArgs []*OperationServiceMockGetByAccountIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OperationServiceMockGetByAccountIDExpectation specifies expectation struct of the OperationService.GetByAccountID
type OperationServiceMockGetByAccountIDExpectation struct {
	mock               *OperationServiceMock
	params             *OperationServiceMockGetByAccountIDParams
	paramPtrs          *OperationServiceMockGetByAccountIDParamPtrs
	expectationOrigins OperationServiceMockGetByAccountIDExpectationOrigins
	results            *OperationServiceMockGetByAccountIDResults
	returnOrigin       string
	Counter            uint64
}

// OperationServiceMockGetByAccountIDParams contains parameters of the OperationService.GetByAccountID
type OperationServiceMockGetByAccountIDParams struct {
	ctx     context.Context
	account int64
	limit   int64
	offset  int64
}

// OperationServiceMockGetByAccountIDParamPtrs contains pointers to parameters of the OperationService.GetByAccountID
type OperationServiceMockGetByAccountIDParamPtrs struct {
	ctx     *context.Context
	account *int64
	limit   *int64
	offset  *int64
}

// OperationServiceMockGetByAccountIDResults contains results of the OperationService.GetByAccountID
type OperationServiceMockGetByAccountIDResults struct {
	oa1 []model.Operation
	err error
}

// OperationServiceMockGetByAccountIDOrigins contains origins of expectations of the OperationService.GetByAccountID
type OperationServiceMockGetByAccountIDExpectationOrigins struct {
	origin        string
	originCtx     string
	originAccount string
	originLimit   string
	originOffset  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) Optional() *mOperationServiceMockGetByAccountID {
	mmGetByAccountID.optional = true
	return mmGetByAccountID
}

// Expect sets up expected params for OperationService.GetByAccountID
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) Expect(ctx context.Context, account int64, limit int64, offset int64) *mOperationServiceMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &OperationServiceMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by ExpectParams functions")
	}

	mmGetByAccountID.defaultExpectation.params = &OperationServiceMockGetByAccountIDParams{ctx, account, limit, offset}
	mmGetByAccountID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByAccountID.expectations {
		if minimock.Equal(e.params, mmGetByAccountID.defaultExpectation.params) {
			mmGetByAccountID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByAccountID.defaultExpectation.params)
		}
	}

	return mmGetByAccountID
}

// ExpectCtxParam1 sets up expected param ctx for OperationService.GetByAccountID
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) ExpectCtxParam1(ctx context.Context) *mOperationServiceMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &OperationServiceMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.params != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Expect")
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs == nil {
		mmGetByAccountID.defaultExpectation.paramPtrs = &OperationServiceMockGetByAccountIDParamPtrs{}
	}
	mmGetByAccountID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByAccountID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByAccountID
}

// ExpectAccountParam2 sets up expected param account for OperationService.GetByAccountID
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) ExpectAccountParam2(account int64) *mOperationServiceMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &OperationServiceMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.params != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Expect")
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs == nil {
		mmGetByAccountID.defaultExpectation.paramPtrs = &OperationServiceMockGetByAccountIDParamPtrs{}
	}
	mmGetByAccountID.defaultExpectation.paramPtrs.account = &account
	mmGetByAccountID.defaultExpectation.expectationOrigins.originAccount = minimock.CallerInfo(1)

	return mmGetByAccountID
}

// ExpectLimitParam3 sets up expected param limit for OperationService.GetByAccountID
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) ExpectLimitParam3(limit int64) *mOperationServiceMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &OperationServiceMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.params != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Expect")
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs == nil {
		mmGetByAccountID.defaultExpectation.paramPtrs = &OperationServiceMockGetByAccountIDParamPtrs{}
	}
	mmGetByAccountID.defaultExpectation.paramPtrs.limit = &limit
	mmGetByAccountID.defaultExpectation.expectationOrigins.originLimit = minimock.CallerInfo(1)

	return mmGetByAccountID
}

// ExpectOffsetParam4 sets up expected param offset for OperationService.GetByAccountID
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) ExpectOffsetParam4(offset int64) *mOperationServiceMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &OperationServiceMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.params != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Expect")
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs == nil {
		mmGetByAccountID.defaultExpectation.paramPtrs = &OperationServiceMockGetByAccountIDParamPtrs{}
	}
	mmGetByAccountID.defaultExpectation.paramPtrs.offset = &offset
	mmGetByAccountID.defaultExpectation.expectationOrigins.originOffset = minimock.CallerInfo(1)

	return mmGetByAccountID
}

// Inspect accepts an inspector function that has same arguments as the OperationService.GetByAccountID
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) Inspect(f func(ctx context.Context, account int64, limit int64, offset int64)) *mOperationServiceMockGetByAccountID {
	if mmGetByAccountID.mock.inspectFuncGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("Inspect function is already set for OperationServiceMock.GetByAccountID")
	}

	mmGetByAccountID.mock.inspectFuncGetByAccountID = f

	return mmGetByAccountID
}

// Return sets up results that will be returned by OperationService.GetByAccountID
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) Return(oa1 []model.Operation, err error) *OperationServiceMock {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &OperationServiceMockGetByAccountIDExpectation{mock: mmGetByAccountID.mock}
	}
	mmGetByAccountID.defaultExpectation.results = &OperationServiceMockGetByAccountIDResults{oa1, err}
	mmGetByAccountID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByAccountID.mock
}

// Set uses given function f to mock the OperationService.GetByAccountID method
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) Set(f func(ctx context.Context, account int64, limit int64, offset int64) (oa1 []model.Operation, err error)) *OperationServiceMock {
	if mmGetByAccountID.defaultExpectation != nil {
		mmGetByAccountID.mock.t.Fatalf("Default expectation is already set for the OperationService.GetByAccountID method")
	}

	if len(mmGetByAccountID.expectations) > 0 {
		mmGetByAccountID.mock.t.Fatalf("Some expectations are already set for the OperationService.GetByAccountID method")
	}

	mmGetByAccountID.mock.funcGetByAccountID = f
	mmGetByAccountID.mock.funcGetByAccountIDOrigin = minimock.CallerInfo(1)
	return mmGetByAccountID.mock
}

// When sets expectation for the OperationService.GetByAccountID which will trigger the result defined by the following
// Then helper
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) When(ctx context.Context, account int64, limit int64, offset int64) *OperationServiceMockGetByAccountIDExpectation {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("OperationServiceMock.GetByAccountID mock is already set by Set")
	}

	expectation := &OperationServiceMockGetByAccountIDExpectation{
		mock:               mmGetByAccountID.mock,
		params:             &OperationServiceMockGetByAccountIDParams{ctx, account, limit, offset},
		expectationOrigins: OperationServiceMockGetByAccountIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByAccountID.expectations = append(mmGetByAccountID.expectations, expectation)
	return expectation
}

// Then sets up OperationService.GetByAccountID return parameters for the expectation previously defined by the When method
func (e *OperationServiceMockGetByAccountIDExpectation) Then(oa1 []model.Operation, err error) *OperationServiceMock {
	e.results = &OperationServiceMockGetByAccountIDResults{oa1, err}
	return e.mock
}

// Times sets number of times OperationService.GetByAccountID should be invoked
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) Times(n uint64) *mOperationServiceMockGetByAccountID {
	if n == 0 {
		mmGetByAccountID.mock.t.Fatalf("Times of OperationServiceMock.GetByAccountID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByAccountID.expectedInvocations, n)
	mmGetByAccountID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByAccountID
}

func (mmGetByAccountID *mOperationServiceMockGetByAccountID) invocationsDone() bool {
	if len(mmGetByAccountID.expectations) == 0 && mmGetByAccountID.defaultExpectation == nil && mmGetByAccountID.mock.funcGetByAccountID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByAccountID.mock.afterGetByAccountIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByAccountID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByAccountID implements OperationService
func (mmGetByAccountID *OperationServiceMock) GetByAccountID(ctx context.Context, account int64, limit int64, offset int64) (oa1 []model.Operation, err error) {
	mm_atomic.AddUint64(&mmGetByAccountID.beforeGetByAccountIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByAccountID.afterGetByAccountIDCounter, 1)

	mmGetByAccountID.t.Helper()

	if mmGetByAccountID.inspectFuncGetByAccountID != nil {
		mmGetByAccountID.inspectFuncGetByAccountID(ctx, account, limit, offset)
	}

	mm_params := OperationServiceMockGetByAccountIDParams{ctx, account, limit, offset}

	// Record call args
	mmGetByAccountID.GetByAccountIDMock.mutex.Lock()
	mmGetByAccountID.GetByAccountIDMock.callArgs = append(mmGetByAccountID.GetByAccountIDMock.callArgs, &mm_params)
	mmGetByAccountID.GetByAccountIDMock.mutex.Unlock()

	for _, e := range mmGetByAccountID.GetByAccountIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.oa1, e.results.err
		}
	}

	if mmGetByAccountID.GetByAccountIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByAccountID.GetByAccountIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByAccountID.GetByAccountIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByAccountID.GetByAccountIDMock.defaultExpectation.paramPtrs

		mm_got := OperationServiceMockGetByAccountIDParams{ctx, account, limit, offset}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByAccountID.t.Errorf("OperationServiceMock.GetByAccountID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.account != nil && !minimock.Equal(*mm_want_ptrs.account, mm_got.account) {
				mmGetByAccountID.t.Errorf("OperationServiceMock.GetByAccountID got unexpected parameter account, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.originAccount, *mm_want_ptrs.account, mm_got.account, minimock.Diff(*mm_want_ptrs.account, mm_got.account))
			}

			if mm_want_ptrs.limit != nil && !minimock.Equal(*mm_want_ptrs.limit, mm_got.limit) {
				mmGetByAccountID.t.Errorf("OperationServiceMock.GetByAccountID got unexpected parameter limit, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.originLimit, *mm_want_ptrs.limit, mm_got.limit, minimock.Diff(*mm_want_ptrs.limit, mm_got.limit))
			}

			if mm_want_ptrs.offset != nil && !minimock.Equal(*mm_want_ptrs.offset, mm_got.offset) {
				mmGetByAccountID.t.Errorf("OperationServiceMock.GetByAccountID got unexpected parameter offset, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.originOffset, *mm_want_ptrs.offset, mm_got.offset, minimock.Diff(*mm_want_ptrs.offset, mm_got.offset))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByAccountID.t.Errorf("OperationServiceMock.GetByAccountID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByAccountID.GetByAccountIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByAccountID.t.Fatal("No results are set for the OperationServiceMock.GetByAccountID")
		}
		return (*mm_results).oa1, (*mm_results).err
	}
	if mmGetByAccountID.funcGetByAccountID != nil {
		return mmGetByAccountID.funcGetByAccountID(ctx, account, limit, offset)
	}
	mmGetByAccountID.t.Fatalf("Unexpected call to OperationServiceMock.GetByAccountID. %v %v %v %v", ctx, account, limit, offset)
	return
}

// GetByAccountIDAfterCounter returns a count of finished OperationServiceMock.GetByAccountID invocations
func (mmGetByAccountID *OperationServiceMock) GetByAccountIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByAccountID.afterGetByAccountIDCounter)
}

// GetByAccountIDBeforeCounter returns a count of OperationServiceMock.GetByAccountID invocations
func (mmGetByAccountID *OperationServiceMock) GetByAccountIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByAccountID.beforeGetByAccountIDCounter)
}

// Calls returns a list of arguments used in each call to OperationServiceMock.GetByAccountID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByAccountID *mOperationServiceMockGetByAccountID) Calls() []*OperationServiceMockGetByAccountIDParams {
	mmGetByAccountID.mutex.RLock()

	argCopy := make([]*OperationServiceMockGetByAccountIDParams, len(mmGetByAccountID.callArgs))
	copy(argCopy, mmGetByAccountID.callArgs)

	mmGetByAccountID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByAccountIDDone returns true if the count of the GetByAccountID invocations corresponds
// the number of defined expectations
func (m *OperationServiceMock) MinimockGetByAccountIDDone() bool {
	if m.GetByAccountIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByAccountIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByAccountIDMock.invocationsDone()
}

// MinimockGetByAccountIDInspect logs each unmet expectation
func (m *OperationServiceMock) MinimockGetByAccountIDInspect() {
	for _, e := range m.GetByAccountIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OperationServiceMock.GetByAccountID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByAccountIDCounter := mm_atomic.LoadUint64(&m.afterGetByAccountIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByAccountIDMock.defaultExpectation != nil && afterGetByAccountIDCounter < 1 {
		if m.GetByAccountIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OperationServiceMock.GetByAccountID at\n%s", m.GetByAccountIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OperationServiceMock.GetByAccountID at\n%s with params: %#v", m.GetByAccountIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByAccountIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByAccountID != nil && afterGetByAccountIDCounter < 1 {
		m.t.Errorf("Expected call to OperationServiceMock.GetByAccountID at\n%s", m.funcGetByAccountIDOrigin)
	}

	if !m.GetByAccountIDMock.invocationsDone() && afterGetByAccountIDCounter > 0 {
		m.t.Errorf("Expected %d calls to OperationServiceMock.GetByAccountID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByAccountIDMock.expectedInvocations), m.GetByAccountIDMock.expectedInvocationsOrigin, afterGetByAccountIDCounter)
	}
}

type mOperationServiceMockUpdate struct {
	optional           bool
	mock               *OperationServiceMock
	defaultExpectation *OperationServiceMockUpdateExpectation
	expectations       []*OperationServiceMockUpdateExpectation

	callArgs []*OperationServiceMockUpdateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OperationServiceMockUpdateExpectation specifies expectation struct of the OperationService.Update
type OperationServiceMockUpdateExpectation struct {
	mock               *OperationServiceMock
	params             *OperationServiceMockUpdateParams
	paramPtrs          *OperationServiceMockUpdateParamPtrs
	expectationOrigins OperationServiceMockUpdateExpectationOrigins
	results            *OperationServiceMockUpdateResults
	returnOrigin       string
	Counter            uint64
}

// OperationServiceMockUpdateParams contains parameters of the OperationService.Update
type OperationServiceMockUpdateParams struct {
	ctx         context.Context
	id          uuid.UUID
	amount      decimal.Decimal
	categoryID  int64
	description string
}

// OperationServiceMockUpdateParamPtrs contains pointers to parameters of the OperationService.Update
type OperationServiceMockUpdateParamPtrs struct {
	ctx         *context.Context
	id          *uuid.UUID
	amount      *decimal.Decimal
	categoryID  *int64
	description *string
}

// OperationServiceMockUpdateResults contains results of the OperationService.Update
type OperationServiceMockUpdateResults struct {
	err error
}

// OperationServiceMockUpdateOrigins contains origins of expectations of the OperationService.Update
type OperationServiceMockUpdateExpectationOrigins struct {
	origin            string
	originCtx         string
	originId          string
	originAmount      string
	originCategoryID  string
	originDescription string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdate *mOperationServiceMockUpdate) Optional() *mOperationServiceMockUpdate {
	mmUpdate.optional = true
	return mmUpdate
}

// Expect sets up expected params for OperationService.Update
func (mmUpdate *mOperationServiceMockUpdate) Expect(ctx context.Context, id uuid.UUID, amount decimal.Decimal, categoryID int64, description string) *mOperationServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &OperationServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.paramPtrs != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by ExpectParams functions")
	}

	mmUpdate.defaultExpectation.params = &OperationServiceMockUpdateParams{ctx, id, amount, categoryID, description}
	mmUpdate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdate.expectations {
		if minimock.Equal(e.params, mmUpdate.defaultExpectation.params) {
			mmUpdate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdate.defaultExpectation.params)
		}
	}

	return mmUpdate
}

// ExpectCtxParam1 sets up expected param ctx for OperationService.Update
func (mmUpdate *mOperationServiceMockUpdate) ExpectCtxParam1(ctx context.Context) *mOperationServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &OperationServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &OperationServiceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.ctx = &ctx
	mmUpdate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmUpdate
}

// ExpectIdParam2 sets up expected param id for OperationService.Update
func (mmUpdate *mOperationServiceMockUpdate) ExpectIdParam2(id uuid.UUID) *mOperationServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &OperationServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &OperationServiceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.id = &id
	mmUpdate.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmUpdate
}

// ExpectAmountParam3 sets up expected param amount for OperationService.Update
func (mmUpdate *mOperationServiceMockUpdate) ExpectAmountParam3(amount decimal.Decimal) *mOperationServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &OperationServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &OperationServiceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.amount = &amount
	mmUpdate.defaultExpectation.expectationOrigins.originAmount = minimock.CallerInfo(1)

	return mmUpdate
}

// ExpectCategoryIDParam4 sets up expected param categoryID for OperationService.Update
func (mmUpdate *mOperationServiceMockUpdate) ExpectCategoryIDParam4(categoryID int64) *mOperationServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &OperationServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &OperationServiceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.categoryID = &categoryID
	mmUpdate.defaultExpectation.expectationOrigins.originCategoryID = minimock.CallerInfo(1)

	return mmUpdate
}

// ExpectDescriptionParam5 sets up expected param description for OperationService.Update
func (mmUpdate *mOperationServiceMockUpdate) ExpectDescriptionParam5(description string) *mOperationServiceMockUpdate {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &OperationServiceMockUpdateExpectation{}
	}

	if mmUpdate.defaultExpectation.params != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Expect")
	}

	if mmUpdate.defaultExpectation.paramPtrs == nil {
		mmUpdate.defaultExpectation.paramPtrs = &OperationServiceMockUpdateParamPtrs{}
	}
	mmUpdate.defaultExpectation.paramPtrs.description = &description
	mmUpdate.defaultExpectation.expectationOrigins.originDescription = minimock.CallerInfo(1)

	return mmUpdate
}

// Inspect accepts an inspector function that has same arguments as the OperationService.Update
func (mmUpdate *mOperationServiceMockUpdate) Inspect(f func(ctx context.Context, id uuid.UUID, amount decimal.Decimal, categoryID int64, description string)) *mOperationServiceMockUpdate {
	if mmUpdate.mock.inspectFuncUpdate != nil {
		mmUpdate.mock.t.Fatalf("Inspect function is already set for OperationServiceMock.Update")
	}

	mmUpdate.mock.inspectFuncUpdate = f

	return mmUpdate
}

// Return sets up results that will be returned by OperationService.Update
func (mmUpdate *mOperationServiceMockUpdate) Return(err error) *OperationServiceMock {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Set")
	}

	if mmUpdate.defaultExpectation == nil {
		mmUpdate.defaultExpectation = &OperationServiceMockUpdateExpectation{mock: mmUpdate.mock}
	}
	mmUpdate.defaultExpectation.results = &OperationServiceMockUpdateResults{err}
	mmUpdate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// Set uses given function f to mock the OperationService.Update method
func (mmUpdate *mOperationServiceMockUpdate) Set(f func(ctx context.Context, id uuid.UUID, amount decimal.Decimal, categoryID int64, description string) (err error)) *OperationServiceMock {
	if mmUpdate.defaultExpectation != nil {
		mmUpdate.mock.t.Fatalf("Default expectation is already set for the OperationService.Update method")
	}

	if len(mmUpdate.expectations) > 0 {
		mmUpdate.mock.t.Fatalf("Some expectations are already set for the OperationService.Update method")
	}

	mmUpdate.mock.funcUpdate = f
	mmUpdate.mock.funcUpdateOrigin = minimock.CallerInfo(1)
	return mmUpdate.mock
}

// When sets expectation for the OperationService.Update which will trigger the result defined by the following
// Then helper
func (mmUpdate *mOperationServiceMockUpdate) When(ctx context.Context, id uuid.UUID, amount decimal.Decimal, categoryID int64, description string) *OperationServiceMockUpdateExpectation {
	if mmUpdate.mock.funcUpdate != nil {
		mmUpdate.mock.t.Fatalf("OperationServiceMock.Update mock is already set by Set")
	}

	expectation := &OperationServiceMockUpdateExpectation{
		mock:               mmUpdate.mock,
		params:             &OperationServiceMockUpdateParams{ctx, id, amount, categoryID, description},
		expectationOrigins: OperationServiceMockUpdateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdate.expectations = append(mmUpdate.expectations, expectation)
	return expectation
}

// Then sets up OperationService.Update return parameters for the expectation previously defined by the When method
func (e *OperationServiceMockUpdateExpectation) Then(err error) *OperationServiceMock {
	e.results = &OperationServiceMockUpdateResults{err}
	return e.mock
}

// Times sets number of times OperationService.Update should be invoked
func (mmUpdate *mOperationServiceMockUpdate) Times(n uint64) *mOperationServiceMockUpdate {
	if n == 0 {
		mmUpdate.mock.t.Fatalf("Times of OperationServiceMock.Update mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdate.expectedInvocations, n)
	mmUpdate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdate
}

func (mmUpdate *mOperationServiceMockUpdate) invocationsDone() bool {
	if len(mmUpdate.expectations) == 0 && mmUpdate.defaultExpectation == nil && mmUpdate.mock.funcUpdate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdate.mock.afterUpdateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Update implements OperationService
func (mmUpdate *OperationServiceMock) Update(ctx context.Context, id uuid.UUID, amount decimal.Decimal, categoryID int64, description string) (err error) {
	mm_atomic.AddUint64(&mmUpdate.beforeUpdateCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdate.afterUpdateCounter, 1)

	mmUpdate.t.Helper()

	if mmUpdate.inspectFuncUpdate != nil {
		mmUpdate.inspectFuncUpdate(ctx, id, amount, categoryID, description)
	}

	mm_params := OperationServiceMockUpdateParams{ctx, id, amount, categoryID, description}

	// Record call args
	mmUpdate.UpdateMock.mutex.Lock()
	mmUpdate.UpdateMock.callArgs = append(mmUpdate.UpdateMock.callArgs, &mm_params)
	mmUpdate.UpdateMock.mutex.Unlock()

	for _, e := range mmUpdate.UpdateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdate.UpdateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdate.UpdateMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdate.UpdateMock.defaultExpectation.params
		mm_want_ptrs := mmUpdate.UpdateMock.defaultExpectation.paramPtrs

		mm_got := OperationServiceMockUpdateParams{ctx, id, amount, categoryID, description}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmUpdate.t.Errorf("OperationServiceMock.Update got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmUpdate.t.Errorf("OperationServiceMock.Update got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

			if mm_want_ptrs.amount != nil && !minimock.Equal(*mm_want_ptrs.amount, mm_got.amount) {
				mmUpdate.t.Errorf("OperationServiceMock.Update got unexpected parameter amount, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originAmount, *mm_want_ptrs.amount, mm_got.amount, minimock.Diff(*mm_want_ptrs.amount, mm_got.amount))
			}

			if mm_want_ptrs.categoryID != nil && !minimock.Equal(*mm_want_ptrs.categoryID, mm_got.categoryID) {
				mmUpdate.t.Errorf("OperationServiceMock.Update got unexpected parameter categoryID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originCategoryID, *mm_want_ptrs.categoryID, mm_got.categoryID, minimock.Diff(*mm_want_ptrs.categoryID, mm_got.categoryID))
			}

			if mm_want_ptrs.description != nil && !minimock.Equal(*mm_want_ptrs.description, mm_got.description) {
				mmUpdate.t.Errorf("OperationServiceMock.Update got unexpected parameter description, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.originDescription, *mm_want_ptrs.description, mm_got.description, minimock.Diff(*mm_want_ptrs.description, mm_got.description))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdate.t.Errorf("OperationServiceMock.Update got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdate.UpdateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdate.UpdateMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdate.t.Fatal("No results are set for the OperationServiceMock.Update")
		}
		return (*mm_results).err
	}
	if mmUpdate.funcUpdate != nil {
		return mmUpdate.funcUpdate(ctx, id, amount, categoryID, description)
	}
	mmUpdate.t.Fatalf("Unexpected call to OperationServiceMock.Update. %v %v %v %v %v", ctx, id, amount, categoryID, description)
	return
}

// UpdateAfterCounter returns a count of finished OperationServiceMock.Update invocations
func (mmUpdate *OperationServiceMock) UpdateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.afterUpdateCounter)
}

// UpdateBeforeCounter returns a count of OperationServiceMock.Update invocations
func (mmUpdate *OperationServiceMock) UpdateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdate.beforeUpdateCounter)
}

// Calls returns a list of arguments used in each call to OperationServiceMock.Update.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdate *mOperationServiceMockUpdate) Calls() []*OperationServiceMockUpdateParams {
	mmUpdate.mutex.RLock()

	argCopy := make([]*OperationServiceMockUpdateParams, len(mmUpdate.callArgs))
	copy(argCopy, mmUpdate.callArgs)

	mmUpdate.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateDone returns true if the count of the Update invocations corresponds
// the number of defined expectations
func (m *OperationServiceMock) MinimockUpdateDone() bool {
	if m.UpdateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateMock.invocationsDone()
}

// MinimockUpdateInspect logs each unmet expectation
func (m *OperationServiceMock) MinimockUpdateInspect() {
	for _, e := range m.UpdateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OperationServiceMock.Update at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateCounter := mm_atomic.LoadUint64(&m.afterUpdateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateMock.defaultExpectation != nil && afterUpdateCounter < 1 {
		if m.UpdateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OperationServiceMock.Update at\n%s", m.UpdateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OperationServiceMock.Update at\n%s with params: %#v", m.UpdateMock.defaultExpectation.expectationOrigins.origin, *m.UpdateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdate != nil && afterUpdateCounter < 1 {
		m.t.Errorf("Expected call to OperationServiceMock.Update at\n%s", m.funcUpdateOrigin)
	}

	if !m.UpdateMock.invocationsDone() && afterUpdateCounter > 0 {
		m.t.Errorf("Expected %d calls to OperationServiceMock.Update at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateMock.expectedInvocations), m.UpdateMock.expectedInvocationsOrigin, afterUpdateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OperationServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockGetByAccountIDInspect()

			m.MinimockUpdateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OperationServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OperationServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockGetByAccountIDDone() &&
		m.MinimockUpdateDone()
}
