// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package account

//go:generate minimock -i github.com/meetmorrowsolonmars/education-pet-project/internal/api/v1/account.AccountService -o account_service_mock_test.go -n AccountServiceMock -p account

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/meetmorrowsolonmars/education-pet-project/internal/domain/model"
)

// AccountServiceMock implements AccountService
type AccountServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, account model.Account) (a1 model.Account, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, account model.Account)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mAccountServiceMockCreate

	funcGetAccountsByUserID          func(ctx context.Context, userID int64) (aa1 []model.Account, err error)
	funcGetAccountsByUserIDOrigin    string
	inspectFuncGetAccountsByUserID   func(ctx context.Context, userID int64)
	afterGetAccountsByUserIDCounter  uint64
	beforeGetAccountsByUserIDCounter uint64
	GetAccountsByUserIDMock          mAccountServiceMockGetAccountsByUserID

	funcGetByID          func(ctx context.Context, id int64) (a1 model.Account, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, id int64)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mAccountServiceMockGetByID
}

// NewAccountServiceMock returns a mock for AccountService
func NewAccountServiceMock(t minimock.Tester) *AccountServiceMock {
	m := &AccountServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mAccountServiceMockCreate{mock: m}
	m.CreateMock.callArgs = []*AccountServiceMockCreateParams{}

	m.GetAccountsByUserIDMock = mAccountServiceMockGetAccountsByUserID{mock: m}
	m.GetAccountsByUserIDMock.callArgs = []*AccountServiceMockGetAccountsByUserIDParams{}

	m.GetByIDMock = mAccountServiceMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*AccountServiceMockGetByIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAccountServiceMockCreate struct {
	optional           bool
	mock               *AccountServiceMock
	defaultExpectation *AccountServiceMockCreateExpectation
	expectations       []*AccountServiceMockCreateExpectation

	callArgs []*AccountServiceMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccountServiceMockCreateExpectation specifies expectation struct of the AccountService.Create
type AccountServiceMockCreateExpectation struct {
	mock               *AccountServiceMock
	params             *AccountServiceMockCreateParams
	paramPtrs          *AccountServiceMockCreateParamPtrs
	expectationOrigins AccountServiceMockCreateExpectationOrigins
	results            *AccountServiceMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// AccountServiceMockCreateParams contains parameters of the AccountService.Create
type AccountServiceMockCreateParams struct {
	ctx     context.Context
	account model.Account
}

// AccountServiceMockCreateParamPtrs contains pointers to parameters of the AccountService.Create
type AccountServiceMockCreateParamPtrs struct {
	ctx     *context.Context
	account *model.Account
}

// AccountServiceMockCreateResults contains results of the AccountService.Create
type AccountServiceMockCreateResults struct {
	a1  model.Account
	err error
}

// AccountServiceMockCreateOrigins contains origins of expectations of the AccountService.Create
type AccountServiceMockCreateExpectationOrigins struct {
	origin        string
	originCtx     string
	originAccount string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mAccountServiceMockCreate) Optional() *mAccountServiceMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for AccountService.Create
func (mmCreate *mAccountServiceMockCreate) Expect(ctx context.Context, account model.Account) *mAccountServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AccountServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AccountServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("AccountServiceMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &AccountServiceMockCreateParams{ctx, account}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for AccountService.Create
func (mmCreate *mAccountServiceMockCreate) ExpectCtxParam1(ctx context.Context) *mAccountServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AccountServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AccountServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("AccountServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &AccountServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectAccountParam2 sets up expected param account for AccountService.Create
func (mmCreate *mAccountServiceMockCreate) ExpectAccountParam2(account model.Account) *mAccountServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AccountServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AccountServiceMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("AccountServiceMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &AccountServiceMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.account = &account
	mmCreate.defaultExpectation.expectationOrigins.originAccount = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the AccountService.Create
func (mmCreate *mAccountServiceMockCreate) Inspect(f func(ctx context.Context, account model.Account)) *mAccountServiceMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for AccountServiceMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by AccountService.Create
func (mmCreate *mAccountServiceMockCreate) Return(a1 model.Account, err error) *AccountServiceMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AccountServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AccountServiceMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &AccountServiceMockCreateResults{a1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the AccountService.Create method
func (mmCreate *mAccountServiceMockCreate) Set(f func(ctx context.Context, account model.Account) (a1 model.Account, err error)) *AccountServiceMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the AccountService.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the AccountService.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the AccountService.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mAccountServiceMockCreate) When(ctx context.Context, account model.Account) *AccountServiceMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AccountServiceMock.Create mock is already set by Set")
	}

	expectation := &AccountServiceMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &AccountServiceMockCreateParams{ctx, account},
		expectationOrigins: AccountServiceMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up AccountService.Create return parameters for the expectation previously defined by the When method
func (e *AccountServiceMockCreateExpectation) Then(a1 model.Account, err error) *AccountServiceMock {
	e.results = &AccountServiceMockCreateResults{a1, err}
	return e.mock
}

// Times sets number of times AccountService.Create should be invoked
func (mmCreate *mAccountServiceMockCreate) Times(n uint64) *mAccountServiceMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of AccountServiceMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mAccountServiceMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements AccountService
func (mmCreate *AccountServiceMock) Create(ctx context.Context, account model.Account) (a1 model.Account, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, account)
	}

	mm_params := AccountServiceMockCreateParams{ctx, account}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.a1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := AccountServiceMockCreateParams{ctx, account}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("AccountServiceMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.account != nil && !minimock.Equal(*mm_want_ptrs.account, mm_got.account) {
				mmCreate.t.Errorf("AccountServiceMock.Create got unexpected parameter account, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originAccount, *mm_want_ptrs.account, mm_got.account, minimock.Diff(*mm_want_ptrs.account, mm_got.account))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("AccountServiceMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the AccountServiceMock.Create")
		}
		return (*mm_results).a1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, account)
	}
	mmCreate.t.Fatalf("Unexpected call to AccountServiceMock.Create. %v %v", ctx, account)
	return
}

// CreateAfterCounter returns a count of finished AccountServiceMock.Create invocations
func (mmCreate *AccountServiceMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of AccountServiceMock.Create invocations
func (mmCreate *AccountServiceMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to AccountServiceMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mAccountServiceMockCreate) Calls() []*AccountServiceMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*AccountServiceMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *AccountServiceMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *AccountServiceMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccountServiceMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccountServiceMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccountServiceMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to AccountServiceMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to AccountServiceMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mAccountServiceMockGetAccountsByUserID struct {
	optional           bool
	mock               *AccountServiceMock
	defaultExpectation *AccountServiceMockGetAccountsByUserIDExpectation
	expectations       []*AccountServiceMockGetAccountsByUserIDExpectation

	callArgs []*AccountServiceMockGetAccountsByUserIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccountServiceMockGetAccountsByUserIDExpectation specifies expectation struct of the AccountService.GetAccountsByUserID
type AccountServiceMockGetAccountsByUserIDExpectation struct {
	mock               *AccountServiceMock
	params             *AccountServiceMockGetAccountsByUserIDParams
	paramPtrs          *AccountServiceMockGetAccountsByUserIDParamPtrs
	expectationOrigins AccountServiceMockGetAccountsByUserIDExpectationOrigins
	results            *AccountServiceMockGetAccountsByUserIDResults
	returnOrigin       string
	Counter            uint64
}

// AccountServiceMockGetAccountsByUserIDParams contains parameters of the AccountService.GetAccountsByUserID
type AccountServiceMockGetAccountsByUserIDParams struct {
	ctx    context.Context
	userID int64
}

// AccountServiceMockGetAccountsByUserIDParamPtrs contains pointers to parameters of the AccountService.GetAccountsByUserID
type AccountServiceMockGetAccountsByUserIDParamPtrs struct {
	ctx    *context.Context
	userID *int64
}

// AccountServiceMockGetAccountsByUserIDResults contains results of the AccountService.GetAccountsByUserID
type AccountServiceMockGetAccountsByUserIDResults struct {
	aa1 []model.Account
	err error
}

// AccountServiceMockGetAccountsByUserIDOrigins contains origins of expectations of the AccountService.GetAccountsByUserID
type AccountServiceMockGetAccountsByUserIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) Optional() *mAccountServiceMockGetAccountsByUserID {
	mmGetAccountsByUserID.optional = true
	return mmGetAccountsByUserID
}

// Expect sets up expected params for AccountService.GetAccountsByUserID
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) Expect(ctx context.Context, userID int64) *mAccountServiceMockGetAccountsByUserID {
	if mmGetAccountsByUserID.mock.funcGetAccountsByUserID != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("AccountServiceMock.GetAccountsByUserID mock is already set by Set")
	}

	if mmGetAccountsByUserID.defaultExpectation == nil {
		mmGetAccountsByUserID.defaultExpectation = &AccountServiceMockGetAccountsByUserIDExpectation{}
	}

	if mmGetAccountsByUserID.defaultExpectation.paramPtrs != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("AccountServiceMock.GetAccountsByUserID mock is already set by ExpectParams functions")
	}

	mmGetAccountsByUserID.defaultExpectation.params = &AccountServiceMockGetAccountsByUserIDParams{ctx, userID}
	mmGetAccountsByUserID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetAccountsByUserID.expectations {
		if minimock.Equal(e.params, mmGetAccountsByUserID.defaultExpectation.params) {
			mmGetAccountsByUserID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetAccountsByUserID.defaultExpectation.params)
		}
	}

	return mmGetAccountsByUserID
}

// ExpectCtxParam1 sets up expected param ctx for AccountService.GetAccountsByUserID
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) ExpectCtxParam1(ctx context.Context) *mAccountServiceMockGetAccountsByUserID {
	if mmGetAccountsByUserID.mock.funcGetAccountsByUserID != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("AccountServiceMock.GetAccountsByUserID mock is already set by Set")
	}

	if mmGetAccountsByUserID.defaultExpectation == nil {
		mmGetAccountsByUserID.defaultExpectation = &AccountServiceMockGetAccountsByUserIDExpectation{}
	}

	if mmGetAccountsByUserID.defaultExpectation.params != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("AccountServiceMock.GetAccountsByUserID mock is already set by Expect")
	}

	if mmGetAccountsByUserID.defaultExpectation.paramPtrs == nil {
		mmGetAccountsByUserID.defaultExpectation.paramPtrs = &AccountServiceMockGetAccountsByUserIDParamPtrs{}
	}
	mmGetAccountsByUserID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetAccountsByUserID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetAccountsByUserID
}

// ExpectUserIDParam2 sets up expected param userID for AccountService.GetAccountsByUserID
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) ExpectUserIDParam2(userID int64) *mAccountServiceMockGetAccountsByUserID {
	if mmGetAccountsByUserID.mock.funcGetAccountsByUserID != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("AccountServiceMock.GetAccountsByUserID mock is already set by Set")
	}

	if mmGetAccountsByUserID.defaultExpectation == nil {
		mmGetAccountsByUserID.defaultExpectation = &AccountServiceMockGetAccountsByUserIDExpectation{}
	}

	if mmGetAccountsByUserID.defaultExpectation.params != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("AccountServiceMock.GetAccountsByUserID mock is already set by Expect")
	}

	if mmGetAccountsByUserID.defaultExpectation.paramPtrs == nil {
		mmGetAccountsByUserID.defaultExpectation.paramPtrs = &AccountServiceMockGetAccountsByUserIDParamPtrs{}
	}
	mmGetAccountsByUserID.defaultExpectation.paramPtrs.userID = &userID
	mmGetAccountsByUserID.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmGetAccountsByUserID
}

// Inspect accepts an inspector function that has same arguments as the AccountService.GetAccountsByUserID
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) Inspect(f func(ctx context.Context, userID int64)) *mAccountServiceMockGetAccountsByUserID {
	if mmGetAccountsByUserID.mock.inspectFuncGetAccountsByUserID != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("Inspect function is already set for AccountServiceMock.GetAccountsByUserID")
	}

	mmGetAccountsByUserID.mock.inspectFuncGetAccountsByUserID = f

	return mmGetAccountsByUserID
}

// Return sets up results that will be returned by AccountService.GetAccountsByUserID
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) Return(aa1 []model.Account, err error) *AccountServiceMock {
	if mmGetAccountsByUserID.mock.funcGetAccountsByUserID != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("AccountServiceMock.GetAccountsByUserID mock is already set by Set")
	}

	if mmGetAccountsByUserID.defaultExpectation == nil {
		mmGetAccountsByUserID.defaultExpectation = &AccountServiceMockGetAccountsByUserIDExpectation{mock: mmGetAccountsByUserID.mock}
	}
	mmGetAccountsByUserID.defaultExpectation.results = &AccountServiceMockGetAccountsByUserIDResults{aa1, err}
	mmGetAccountsByUserID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetAccountsByUserID.mock
}

// Set uses given function f to mock the AccountService.GetAccountsByUserID method
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) Set(f func(ctx context.Context, userID int64) (aa1 []model.Account, err error)) *AccountServiceMock {
	if mmGetAccountsByUserID.defaultExpectation != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("Default expectation is already set for the AccountService.GetAccountsByUserID method")
	}

	if len(mmGetAccountsByUserID.expectations) > 0 {
		mmGetAccountsByUserID.mock.t.Fatalf("Some expectations are already set for the AccountService.GetAccountsByUserID method")
	}

	mmGetAccountsByUserID.mock.funcGetAccountsByUserID = f
	mmGetAccountsByUserID.mock.funcGetAccountsByUserIDOrigin = minimock.CallerInfo(1)
	return mmGetAccountsByUserID.mock
}

// When sets expectation for the AccountService.GetAccountsByUserID which will trigger the result defined by the following
// Then helper
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) When(ctx context.Context, userID int64) *AccountServiceMockGetAccountsByUserIDExpectation {
	if mmGetAccountsByUserID.mock.funcGetAccountsByUserID != nil {
		mmGetAccountsByUserID.mock.t.Fatalf("AccountServiceMock.GetAccountsByUserID mock is already set by Set")
	}

	expectation := &AccountServiceMockGetAccountsByUserIDExpectation{
		mock:               mmGetAccountsByUserID.mock,
		params:             &AccountServiceMockGetAccountsByUserIDParams{ctx, userID},
		expectationOrigins: AccountServiceMockGetAccountsByUserIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetAccountsByUserID.expectations = append(mmGetAccountsByUserID.expectations, expectation)
	return expectation
}

// Then sets up AccountService.GetAccountsByUserID return parameters for the expectation previously defined by the When method
func (e *AccountServiceMockGetAccountsByUserIDExpectation) Then(aa1 []model.Account, err error) *AccountServiceMock {
	e.results = &AccountServiceMockGetAccountsByUserIDResults{aa1, err}
	return e.mock
}

// Times sets number of times AccountService.GetAccountsByUserID should be invoked
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) Times(n uint64) *mAccountServiceMockGetAccountsByUserID {
	if n == 0 {
		mmGetAccountsByUserID.mock.t.Fatalf("Times of AccountServiceMock.GetAccountsByUserID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetAccountsByUserID.expectedInvocations, n)
	mmGetAccountsByUserID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetAccountsByUserID
}

func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) invocationsDone() bool {
	if len(mmGetAccountsByUserID.expectations) == 0 && mmGetAccountsByUserID.defaultExpectation == nil && mmGetAccountsByUserID.mock.funcGetAccountsByUserID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetAccountsByUserID.mock.afterGetAccountsByUserIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetAccountsByUserID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetAccountsByUserID implements AccountService
func (mmGetAccountsByUserID *AccountServiceMock) GetAccountsByUserID(ctx context.Context, userID int64) (aa1 []model.Account, err error) {
	mm_atomic.AddUint64(&mmGetAccountsByUserID.beforeGetAccountsByUserIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAccountsByUserID.afterGetAccountsByUserIDCounter, 1)

	mmGetAccountsByUserID.t.Helper()

	if mmGetAccountsByUserID.inspectFuncGetAccountsByUserID != nil {
		mmGetAccountsByUserID.inspectFuncGetAccountsByUserID(ctx, userID)
	}

	mm_params := AccountServiceMockGetAccountsByUserIDParams{ctx, userID}

	// Record call args
	mmGetAccountsByUserID.GetAccountsByUserIDMock.mutex.Lock()
	mmGetAccountsByUserID.GetAccountsByUserIDMock.callArgs = append(mmGetAccountsByUserID.GetAccountsByUserIDMock.callArgs, &mm_params)
	mmGetAccountsByUserID.GetAccountsByUserIDMock.mutex.Unlock()

	for _, e := range mmGetAccountsByUserID.GetAccountsByUserIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.aa1, e.results.err
		}
	}

	if mmGetAccountsByUserID.GetAccountsByUserIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAccountsByUserID.GetAccountsByUserIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetAccountsByUserID.GetAccountsByUserIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetAccountsByUserID.GetAccountsByUserIDMock.defaultExpectation.paramPtrs

		mm_got := AccountServiceMockGetAccountsByUserIDParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetAccountsByUserID.t.Errorf("AccountServiceMock.GetAccountsByUserID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAccountsByUserID.GetAccountsByUserIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmGetAccountsByUserID.t.Errorf("AccountServiceMock.GetAccountsByUserID got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAccountsByUserID.GetAccountsByUserIDMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetAccountsByUserID.t.Errorf("AccountServiceMock.GetAccountsByUserID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetAccountsByUserID.GetAccountsByUserIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetAccountsByUserID.GetAccountsByUserIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAccountsByUserID.t.Fatal("No results are set for the AccountServiceMock.GetAccountsByUserID")
		}
		return (*mm_results).aa1, (*mm_results).err
	}
	if mmGetAccountsByUserID.funcGetAccountsByUserID != nil {
		return mmGetAccountsByUserID.funcGetAccountsByUserID(ctx, userID)
	}
	mmGetAccountsByUserID.t.Fatalf("Unexpected call to AccountServiceMock.GetAccountsByUserID. %v %v", ctx, userID)
	return
}

// GetAccountsByUserIDAfterCounter returns a count of finished AccountServiceMock.GetAccountsByUserID invocations
func (mmGetAccountsByUserID *AccountServiceMock) GetAccountsByUserIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAccountsByUserID.afterGetAccountsByUserIDCounter)
}

// GetAccountsByUserIDBeforeCounter returns a count of AccountServiceMock.GetAccountsByUserID invocations
func (mmGetAccountsByUserID *AccountServiceMock) GetAccountsByUserIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAccountsByUserID.beforeGetAccountsByUserIDCounter)
}

// Calls returns a list of arguments used in each call to AccountServiceMock.GetAccountsByUserID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetAccountsByUserID *mAccountServiceMockGetAccountsByUserID) Calls() []*AccountServiceMockGetAccountsByUserIDParams {
	mmGetAccountsByUserID.mutex.RLock()

	argCopy := make([]*AccountServiceMockGetAccountsByUserIDParams, len(mmGetAccountsByUserID.callArgs))
	copy(argCopy, mmGetAccountsByUserID.callArgs)

	mmGetAccountsByUserID.mutex.RUnlock()

	return argCopy
}

// MinimockGetAccountsByUserIDDone returns true if the count of the GetAccountsByUserID invocations corresponds
// the number of defined expectations
func (m *AccountServiceMock) MinimockGetAccountsByUserIDDone() bool {
	if m.GetAccountsByUserIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetAccountsByUserIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetAccountsByUserIDMock.invocationsDone()
}

// MinimockGetAccountsByUserIDInspect logs each unmet expectation
func (m *AccountServiceMock) MinimockGetAccountsByUserIDInspect() {
	for _, e := range m.GetAccountsByUserIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccountServiceMock.GetAccountsByUserID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetAccountsByUserIDCounter := mm_atomic.LoadUint64(&m.afterGetAccountsByUserIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetAccountsByUserIDMock.defaultExpectation != nil && afterGetAccountsByUserIDCounter < 1 {
		if m.GetAccountsByUserIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccountServiceMock.GetAccountsByUserID at\n%s", m.GetAccountsByUserIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccountServiceMock.GetAccountsByUserID at\n%s with params: %#v", m.GetAccountsByUserIDMock.defaultExpectation.expectationOrigins.origin, *m.GetAccountsByUserIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAccountsByUserID != nil && afterGetAccountsByUserIDCounter < 1 {
		m.t.Errorf("Expected call to AccountServiceMock.GetAccountsByUserID at\n%s", m.funcGetAccountsByUserIDOrigin)
	}

	if !m.GetAccountsByUserIDMock.invocationsDone() && afterGetAccountsByUserIDCounter > 0 {
		m.t.Errorf("Expected %d calls to AccountServiceMock.GetAccountsByUserID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetAccountsByUserIDMock.expectedInvocations), m.GetAccountsByUserIDMock.expectedInvocationsOrigin, afterGetAccountsByUserIDCounter)
	}
}

type mAccountServiceMockGetByID struct {
	optional           bool
	mock               *AccountServiceMock
	defaultExpectation *AccountServiceMockGetByIDExpectation
	expectations       []*AccountServiceMockGetByIDExpectation

	callArgs []*AccountServiceMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AccountServiceMockGetByIDExpectation specifies expectation struct of the AccountService.GetByID
type AccountServiceMockGetByIDExpectation struct {
	mock               *AccountServiceMock
	params             *AccountServiceMockGetByIDParams
	paramPtrs          *AccountServiceMockGetByIDParamPtrs
	expectationOrigins AccountServiceMockGetByIDExpectationOrigins
	results            *AccountServiceMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// AccountServiceMockGetByIDParams contains parameters of the AccountService.GetByID
type AccountServiceMockGetByIDParams struct {
	ctx context.Context
	id  int64
}

// AccountServiceMockGetByIDParamPtrs contains pointers to parameters of the AccountService.GetByID
type AccountServiceMockGetByIDParamPtrs struct {
	ctx *context.Context
	id  *int64
}

// AccountServiceMockGetByIDResults contains results of the AccountService.GetByID
type AccountServiceMockGetByIDResults struct {
	a1  model.Account
	err error
}

// AccountServiceMockGetByIDOrigins contains origins of expectations of the AccountService.GetByID
type AccountServiceMockGetByIDExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mAccountServiceMockGetByID) Optional() *mAccountServiceMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for AccountService.GetByID
func (mmGetByID *mAccountServiceMockGetByID) Expect(ctx context.Context, id int64) *mAccountServiceMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("AccountServiceMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &AccountServiceMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("AccountServiceMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &AccountServiceMockGetByIDParams{ctx, id}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for AccountService.GetByID
func (mmGetByID *mAccountServiceMockGetByID) ExpectCtxParam1(ctx context.Context) *mAccountServiceMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("AccountServiceMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &AccountServiceMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("AccountServiceMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &AccountServiceMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectIdParam2 sets up expected param id for AccountService.GetByID
func (mmGetByID *mAccountServiceMockGetByID) ExpectIdParam2(id int64) *mAccountServiceMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("AccountServiceMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &AccountServiceMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("AccountServiceMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &AccountServiceMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.id = &id
	mmGetByID.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the AccountService.GetByID
func (mmGetByID *mAccountServiceMockGetByID) Inspect(f func(ctx context.Context, id int64)) *mAccountServiceMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for AccountServiceMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by AccountService.GetByID
func (mmGetByID *mAccountServiceMockGetByID) Return(a1 model.Account, err error) *AccountServiceMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("AccountServiceMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &AccountServiceMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &AccountServiceMockGetByIDResults{a1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the AccountService.GetByID method
func (mmGetByID *mAccountServiceMockGetByID) Set(f func(ctx context.Context, id int64) (a1 model.Account, err error)) *AccountServiceMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the AccountService.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the AccountService.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the AccountService.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mAccountServiceMockGetByID) When(ctx context.Context, id int64) *AccountServiceMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("AccountServiceMock.GetByID mock is already set by Set")
	}

	expectation := &AccountServiceMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &AccountServiceMockGetByIDParams{ctx, id},
		expectationOrigins: AccountServiceMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up AccountService.GetByID return parameters for the expectation previously defined by the When method
func (e *AccountServiceMockGetByIDExpectation) Then(a1 model.Account, err error) *AccountServiceMock {
	e.results = &AccountServiceMockGetByIDResults{a1, err}
	return e.mock
}

// Times sets number of times AccountService.GetByID should be invoked
func (mmGetByID *mAccountServiceMockGetByID) Times(n uint64) *mAccountServiceMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of AccountServiceMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mAccountServiceMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements AccountService
func (mmGetByID *AccountServiceMock) GetByID(ctx context.Context, id int64) (a1 model.Account, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, id)
	}

	mm_params := AccountServiceMockGetByIDParams{ctx, id}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.a1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := AccountServiceMockGetByIDParams{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("AccountServiceMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetByID.t.Errorf("AccountServiceMock.GetByID got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("AccountServiceMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the AccountServiceMock.GetByID")
		}
		return (*mm_results).a1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, id)
	}
	mmGetByID.t.Fatalf("Unexpected call to AccountServiceMock.GetByID. %v %v", ctx, id)
	return
}

// GetByIDAfterCounter returns a count of finished AccountServiceMock.GetByID invocations
func (mmGetByID *AccountServiceMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of AccountServiceMock.GetByID invocations
func (mmGetByID *AccountServiceMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to AccountServiceMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mAccountServiceMockGetByID) Calls() []*AccountServiceMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*AccountServiceMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *AccountServiceMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *AccountServiceMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AccountServiceMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AccountServiceMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AccountServiceMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to AccountServiceMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to AccountServiceMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AccountServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetAccountsByUserIDInspect()

			m.MinimockGetByIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AccountServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AccountServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetAccountsByUserIDDone() &&
		m.MinimockGetByIDDone()
}
