volumes:
  prom_data:
  pg_data:

services:
  postgres:
    image: postgres:17-alpine3.22
    container_name: postgres
    restart: unless-stopped
    command: >
      --log_statement=all
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "25432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.135.0
    container_name: otel_collector
    restart: unless-stopped
    command: >
      --config=/etc/otel-collector.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4317:4317"
    volumes:
      - "./deployments/opentelemetry/otel-collector.yaml:/etc/otel-collector.yaml"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command: >
      --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - "./deployments/prometheus:/etc/prometheus"
      - "prom_data:/prometheus"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=grafana"
    volumes:
      - ./deployments/grafana:/etc/grafana/provisioning/datasources
  tempo:
    image: grafana/tempo:main-79bbab4
    restart: unless-stopped
    command: >
      -config.file=/etc/tempo.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3200:3200"
      - "4320:4320"
    volumes:
      - "./deployments/grafana/tempo.yaml:/etc/tempo.yaml"
