// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package operation

//go:generate minimock -i github.com/meetmorrowsolonmars/education-pet-project/internal/domain/operation.Store -o store_mock_test.go -n StoreMock -p operation

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/meetmorrowsolonmars/education-pet-project/internal/domain/model"
)

// StoreMock implements Store
type StoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, operation model.Operation) (o1 model.Operation, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, operation model.Operation)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mStoreMockCreate

	funcGetByAccountID          func(ctx context.Context, accountID int64, limit int64, offset int64) (oa1 []model.Operation, err error)
	funcGetByAccountIDOrigin    string
	inspectFuncGetByAccountID   func(ctx context.Context, accountID int64, limit int64, offset int64)
	afterGetByAccountIDCounter  uint64
	beforeGetByAccountIDCounter uint64
	GetByAccountIDMock          mStoreMockGetByAccountID
}

// NewStoreMock returns a mock for Store
func NewStoreMock(t minimock.Tester) *StoreMock {
	m := &StoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mStoreMockCreate{mock: m}
	m.CreateMock.callArgs = []*StoreMockCreateParams{}

	m.GetByAccountIDMock = mStoreMockGetByAccountID{mock: m}
	m.GetByAccountIDMock.callArgs = []*StoreMockGetByAccountIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStoreMockCreate struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockCreateExpectation
	expectations       []*StoreMockCreateExpectation

	callArgs []*StoreMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockCreateExpectation specifies expectation struct of the Store.Create
type StoreMockCreateExpectation struct {
	mock               *StoreMock
	params             *StoreMockCreateParams
	paramPtrs          *StoreMockCreateParamPtrs
	expectationOrigins StoreMockCreateExpectationOrigins
	results            *StoreMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockCreateParams contains parameters of the Store.Create
type StoreMockCreateParams struct {
	ctx       context.Context
	operation model.Operation
}

// StoreMockCreateParamPtrs contains pointers to parameters of the Store.Create
type StoreMockCreateParamPtrs struct {
	ctx       *context.Context
	operation *model.Operation
}

// StoreMockCreateResults contains results of the Store.Create
type StoreMockCreateResults struct {
	o1  model.Operation
	err error
}

// StoreMockCreateOrigins contains origins of expectations of the Store.Create
type StoreMockCreateExpectationOrigins struct {
	origin          string
	originCtx       string
	originOperation string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mStoreMockCreate) Optional() *mStoreMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for Store.Create
func (mmCreate *mStoreMockCreate) Expect(ctx context.Context, operation model.Operation) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &StoreMockCreateParams{ctx, operation}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for Store.Create
func (mmCreate *mStoreMockCreate) ExpectCtxParam1(ctx context.Context) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &StoreMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectOperationParam2 sets up expected param operation for Store.Create
func (mmCreate *mStoreMockCreate) ExpectOperationParam2(operation model.Operation) *mStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &StoreMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.operation = &operation
	mmCreate.defaultExpectation.expectationOrigins.originOperation = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the Store.Create
func (mmCreate *mStoreMockCreate) Inspect(f func(ctx context.Context, operation model.Operation)) *mStoreMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for StoreMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by Store.Create
func (mmCreate *mStoreMockCreate) Return(o1 model.Operation, err error) *StoreMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &StoreMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &StoreMockCreateResults{o1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the Store.Create method
func (mmCreate *mStoreMockCreate) Set(f func(ctx context.Context, operation model.Operation) (o1 model.Operation, err error)) *StoreMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the Store.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the Store.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the Store.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mStoreMockCreate) When(ctx context.Context, operation model.Operation) *StoreMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("StoreMock.Create mock is already set by Set")
	}

	expectation := &StoreMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &StoreMockCreateParams{ctx, operation},
		expectationOrigins: StoreMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up Store.Create return parameters for the expectation previously defined by the When method
func (e *StoreMockCreateExpectation) Then(o1 model.Operation, err error) *StoreMock {
	e.results = &StoreMockCreateResults{o1, err}
	return e.mock
}

// Times sets number of times Store.Create should be invoked
func (mmCreate *mStoreMockCreate) Times(n uint64) *mStoreMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of StoreMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mStoreMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements Store
func (mmCreate *StoreMock) Create(ctx context.Context, operation model.Operation) (o1 model.Operation, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, operation)
	}

	mm_params := StoreMockCreateParams{ctx, operation}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.o1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := StoreMockCreateParams{ctx, operation}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("StoreMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.operation != nil && !minimock.Equal(*mm_want_ptrs.operation, mm_got.operation) {
				mmCreate.t.Errorf("StoreMock.Create got unexpected parameter operation, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originOperation, *mm_want_ptrs.operation, mm_got.operation, minimock.Diff(*mm_want_ptrs.operation, mm_got.operation))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("StoreMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the StoreMock.Create")
		}
		return (*mm_results).o1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, operation)
	}
	mmCreate.t.Fatalf("Unexpected call to StoreMock.Create. %v %v", ctx, operation)
	return
}

// CreateAfterCounter returns a count of finished StoreMock.Create invocations
func (mmCreate *StoreMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of StoreMock.Create invocations
func (mmCreate *StoreMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mStoreMockCreate) Calls() []*StoreMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*StoreMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *StoreMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mStoreMockGetByAccountID struct {
	optional           bool
	mock               *StoreMock
	defaultExpectation *StoreMockGetByAccountIDExpectation
	expectations       []*StoreMockGetByAccountIDExpectation

	callArgs []*StoreMockGetByAccountIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StoreMockGetByAccountIDExpectation specifies expectation struct of the Store.GetByAccountID
type StoreMockGetByAccountIDExpectation struct {
	mock               *StoreMock
	params             *StoreMockGetByAccountIDParams
	paramPtrs          *StoreMockGetByAccountIDParamPtrs
	expectationOrigins StoreMockGetByAccountIDExpectationOrigins
	results            *StoreMockGetByAccountIDResults
	returnOrigin       string
	Counter            uint64
}

// StoreMockGetByAccountIDParams contains parameters of the Store.GetByAccountID
type StoreMockGetByAccountIDParams struct {
	ctx       context.Context
	accountID int64
	limit     int64
	offset    int64
}

// StoreMockGetByAccountIDParamPtrs contains pointers to parameters of the Store.GetByAccountID
type StoreMockGetByAccountIDParamPtrs struct {
	ctx       *context.Context
	accountID *int64
	limit     *int64
	offset    *int64
}

// StoreMockGetByAccountIDResults contains results of the Store.GetByAccountID
type StoreMockGetByAccountIDResults struct {
	oa1 []model.Operation
	err error
}

// StoreMockGetByAccountIDOrigins contains origins of expectations of the Store.GetByAccountID
type StoreMockGetByAccountIDExpectationOrigins struct {
	origin          string
	originCtx       string
	originAccountID string
	originLimit     string
	originOffset    string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByAccountID *mStoreMockGetByAccountID) Optional() *mStoreMockGetByAccountID {
	mmGetByAccountID.optional = true
	return mmGetByAccountID
}

// Expect sets up expected params for Store.GetByAccountID
func (mmGetByAccountID *mStoreMockGetByAccountID) Expect(ctx context.Context, accountID int64, limit int64, offset int64) *mStoreMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &StoreMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by ExpectParams functions")
	}

	mmGetByAccountID.defaultExpectation.params = &StoreMockGetByAccountIDParams{ctx, accountID, limit, offset}
	mmGetByAccountID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByAccountID.expectations {
		if minimock.Equal(e.params, mmGetByAccountID.defaultExpectation.params) {
			mmGetByAccountID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByAccountID.defaultExpectation.params)
		}
	}

	return mmGetByAccountID
}

// ExpectCtxParam1 sets up expected param ctx for Store.GetByAccountID
func (mmGetByAccountID *mStoreMockGetByAccountID) ExpectCtxParam1(ctx context.Context) *mStoreMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &StoreMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.params != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Expect")
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs == nil {
		mmGetByAccountID.defaultExpectation.paramPtrs = &StoreMockGetByAccountIDParamPtrs{}
	}
	mmGetByAccountID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByAccountID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByAccountID
}

// ExpectAccountIDParam2 sets up expected param accountID for Store.GetByAccountID
func (mmGetByAccountID *mStoreMockGetByAccountID) ExpectAccountIDParam2(accountID int64) *mStoreMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &StoreMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.params != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Expect")
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs == nil {
		mmGetByAccountID.defaultExpectation.paramPtrs = &StoreMockGetByAccountIDParamPtrs{}
	}
	mmGetByAccountID.defaultExpectation.paramPtrs.accountID = &accountID
	mmGetByAccountID.defaultExpectation.expectationOrigins.originAccountID = minimock.CallerInfo(1)

	return mmGetByAccountID
}

// ExpectLimitParam3 sets up expected param limit for Store.GetByAccountID
func (mmGetByAccountID *mStoreMockGetByAccountID) ExpectLimitParam3(limit int64) *mStoreMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &StoreMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.params != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Expect")
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs == nil {
		mmGetByAccountID.defaultExpectation.paramPtrs = &StoreMockGetByAccountIDParamPtrs{}
	}
	mmGetByAccountID.defaultExpectation.paramPtrs.limit = &limit
	mmGetByAccountID.defaultExpectation.expectationOrigins.originLimit = minimock.CallerInfo(1)

	return mmGetByAccountID
}

// ExpectOffsetParam4 sets up expected param offset for Store.GetByAccountID
func (mmGetByAccountID *mStoreMockGetByAccountID) ExpectOffsetParam4(offset int64) *mStoreMockGetByAccountID {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &StoreMockGetByAccountIDExpectation{}
	}

	if mmGetByAccountID.defaultExpectation.params != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Expect")
	}

	if mmGetByAccountID.defaultExpectation.paramPtrs == nil {
		mmGetByAccountID.defaultExpectation.paramPtrs = &StoreMockGetByAccountIDParamPtrs{}
	}
	mmGetByAccountID.defaultExpectation.paramPtrs.offset = &offset
	mmGetByAccountID.defaultExpectation.expectationOrigins.originOffset = minimock.CallerInfo(1)

	return mmGetByAccountID
}

// Inspect accepts an inspector function that has same arguments as the Store.GetByAccountID
func (mmGetByAccountID *mStoreMockGetByAccountID) Inspect(f func(ctx context.Context, accountID int64, limit int64, offset int64)) *mStoreMockGetByAccountID {
	if mmGetByAccountID.mock.inspectFuncGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("Inspect function is already set for StoreMock.GetByAccountID")
	}

	mmGetByAccountID.mock.inspectFuncGetByAccountID = f

	return mmGetByAccountID
}

// Return sets up results that will be returned by Store.GetByAccountID
func (mmGetByAccountID *mStoreMockGetByAccountID) Return(oa1 []model.Operation, err error) *StoreMock {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Set")
	}

	if mmGetByAccountID.defaultExpectation == nil {
		mmGetByAccountID.defaultExpectation = &StoreMockGetByAccountIDExpectation{mock: mmGetByAccountID.mock}
	}
	mmGetByAccountID.defaultExpectation.results = &StoreMockGetByAccountIDResults{oa1, err}
	mmGetByAccountID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByAccountID.mock
}

// Set uses given function f to mock the Store.GetByAccountID method
func (mmGetByAccountID *mStoreMockGetByAccountID) Set(f func(ctx context.Context, accountID int64, limit int64, offset int64) (oa1 []model.Operation, err error)) *StoreMock {
	if mmGetByAccountID.defaultExpectation != nil {
		mmGetByAccountID.mock.t.Fatalf("Default expectation is already set for the Store.GetByAccountID method")
	}

	if len(mmGetByAccountID.expectations) > 0 {
		mmGetByAccountID.mock.t.Fatalf("Some expectations are already set for the Store.GetByAccountID method")
	}

	mmGetByAccountID.mock.funcGetByAccountID = f
	mmGetByAccountID.mock.funcGetByAccountIDOrigin = minimock.CallerInfo(1)
	return mmGetByAccountID.mock
}

// When sets expectation for the Store.GetByAccountID which will trigger the result defined by the following
// Then helper
func (mmGetByAccountID *mStoreMockGetByAccountID) When(ctx context.Context, accountID int64, limit int64, offset int64) *StoreMockGetByAccountIDExpectation {
	if mmGetByAccountID.mock.funcGetByAccountID != nil {
		mmGetByAccountID.mock.t.Fatalf("StoreMock.GetByAccountID mock is already set by Set")
	}

	expectation := &StoreMockGetByAccountIDExpectation{
		mock:               mmGetByAccountID.mock,
		params:             &StoreMockGetByAccountIDParams{ctx, accountID, limit, offset},
		expectationOrigins: StoreMockGetByAccountIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByAccountID.expectations = append(mmGetByAccountID.expectations, expectation)
	return expectation
}

// Then sets up Store.GetByAccountID return parameters for the expectation previously defined by the When method
func (e *StoreMockGetByAccountIDExpectation) Then(oa1 []model.Operation, err error) *StoreMock {
	e.results = &StoreMockGetByAccountIDResults{oa1, err}
	return e.mock
}

// Times sets number of times Store.GetByAccountID should be invoked
func (mmGetByAccountID *mStoreMockGetByAccountID) Times(n uint64) *mStoreMockGetByAccountID {
	if n == 0 {
		mmGetByAccountID.mock.t.Fatalf("Times of StoreMock.GetByAccountID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByAccountID.expectedInvocations, n)
	mmGetByAccountID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByAccountID
}

func (mmGetByAccountID *mStoreMockGetByAccountID) invocationsDone() bool {
	if len(mmGetByAccountID.expectations) == 0 && mmGetByAccountID.defaultExpectation == nil && mmGetByAccountID.mock.funcGetByAccountID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByAccountID.mock.afterGetByAccountIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByAccountID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByAccountID implements Store
func (mmGetByAccountID *StoreMock) GetByAccountID(ctx context.Context, accountID int64, limit int64, offset int64) (oa1 []model.Operation, err error) {
	mm_atomic.AddUint64(&mmGetByAccountID.beforeGetByAccountIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByAccountID.afterGetByAccountIDCounter, 1)

	mmGetByAccountID.t.Helper()

	if mmGetByAccountID.inspectFuncGetByAccountID != nil {
		mmGetByAccountID.inspectFuncGetByAccountID(ctx, accountID, limit, offset)
	}

	mm_params := StoreMockGetByAccountIDParams{ctx, accountID, limit, offset}

	// Record call args
	mmGetByAccountID.GetByAccountIDMock.mutex.Lock()
	mmGetByAccountID.GetByAccountIDMock.callArgs = append(mmGetByAccountID.GetByAccountIDMock.callArgs, &mm_params)
	mmGetByAccountID.GetByAccountIDMock.mutex.Unlock()

	for _, e := range mmGetByAccountID.GetByAccountIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.oa1, e.results.err
		}
	}

	if mmGetByAccountID.GetByAccountIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByAccountID.GetByAccountIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByAccountID.GetByAccountIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByAccountID.GetByAccountIDMock.defaultExpectation.paramPtrs

		mm_got := StoreMockGetByAccountIDParams{ctx, accountID, limit, offset}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByAccountID.t.Errorf("StoreMock.GetByAccountID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.accountID != nil && !minimock.Equal(*mm_want_ptrs.accountID, mm_got.accountID) {
				mmGetByAccountID.t.Errorf("StoreMock.GetByAccountID got unexpected parameter accountID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.originAccountID, *mm_want_ptrs.accountID, mm_got.accountID, minimock.Diff(*mm_want_ptrs.accountID, mm_got.accountID))
			}

			if mm_want_ptrs.limit != nil && !minimock.Equal(*mm_want_ptrs.limit, mm_got.limit) {
				mmGetByAccountID.t.Errorf("StoreMock.GetByAccountID got unexpected parameter limit, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.originLimit, *mm_want_ptrs.limit, mm_got.limit, minimock.Diff(*mm_want_ptrs.limit, mm_got.limit))
			}

			if mm_want_ptrs.offset != nil && !minimock.Equal(*mm_want_ptrs.offset, mm_got.offset) {
				mmGetByAccountID.t.Errorf("StoreMock.GetByAccountID got unexpected parameter offset, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.originOffset, *mm_want_ptrs.offset, mm_got.offset, minimock.Diff(*mm_want_ptrs.offset, mm_got.offset))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByAccountID.t.Errorf("StoreMock.GetByAccountID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByAccountID.GetByAccountIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByAccountID.GetByAccountIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByAccountID.t.Fatal("No results are set for the StoreMock.GetByAccountID")
		}
		return (*mm_results).oa1, (*mm_results).err
	}
	if mmGetByAccountID.funcGetByAccountID != nil {
		return mmGetByAccountID.funcGetByAccountID(ctx, accountID, limit, offset)
	}
	mmGetByAccountID.t.Fatalf("Unexpected call to StoreMock.GetByAccountID. %v %v %v %v", ctx, accountID, limit, offset)
	return
}

// GetByAccountIDAfterCounter returns a count of finished StoreMock.GetByAccountID invocations
func (mmGetByAccountID *StoreMock) GetByAccountIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByAccountID.afterGetByAccountIDCounter)
}

// GetByAccountIDBeforeCounter returns a count of StoreMock.GetByAccountID invocations
func (mmGetByAccountID *StoreMock) GetByAccountIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByAccountID.beforeGetByAccountIDCounter)
}

// Calls returns a list of arguments used in each call to StoreMock.GetByAccountID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByAccountID *mStoreMockGetByAccountID) Calls() []*StoreMockGetByAccountIDParams {
	mmGetByAccountID.mutex.RLock()

	argCopy := make([]*StoreMockGetByAccountIDParams, len(mmGetByAccountID.callArgs))
	copy(argCopy, mmGetByAccountID.callArgs)

	mmGetByAccountID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByAccountIDDone returns true if the count of the GetByAccountID invocations corresponds
// the number of defined expectations
func (m *StoreMock) MinimockGetByAccountIDDone() bool {
	if m.GetByAccountIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByAccountIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByAccountIDMock.invocationsDone()
}

// MinimockGetByAccountIDInspect logs each unmet expectation
func (m *StoreMock) MinimockGetByAccountIDInspect() {
	for _, e := range m.GetByAccountIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StoreMock.GetByAccountID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByAccountIDCounter := mm_atomic.LoadUint64(&m.afterGetByAccountIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByAccountIDMock.defaultExpectation != nil && afterGetByAccountIDCounter < 1 {
		if m.GetByAccountIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StoreMock.GetByAccountID at\n%s", m.GetByAccountIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StoreMock.GetByAccountID at\n%s with params: %#v", m.GetByAccountIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByAccountIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByAccountID != nil && afterGetByAccountIDCounter < 1 {
		m.t.Errorf("Expected call to StoreMock.GetByAccountID at\n%s", m.funcGetByAccountIDOrigin)
	}

	if !m.GetByAccountIDMock.invocationsDone() && afterGetByAccountIDCounter > 0 {
		m.t.Errorf("Expected %d calls to StoreMock.GetByAccountID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByAccountIDMock.expectedInvocations), m.GetByAccountIDMock.expectedInvocationsOrigin, afterGetByAccountIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetByAccountIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetByAccountIDDone()
}
