// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package v1

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/meetmorrowsolonmars/education-pet-project/internal/domain"
)

// UserStoreMock implements UserStore
type UserStoreMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, user domain.User) (u1 domain.User, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, user domain.User)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mUserStoreMockCreate

	funcGetByEmail          func(ctx context.Context, email string) (u1 domain.User, err error)
	funcGetByEmailOrigin    string
	inspectFuncGetByEmail   func(ctx context.Context, email string)
	afterGetByEmailCounter  uint64
	beforeGetByEmailCounter uint64
	GetByEmailMock          mUserStoreMockGetByEmail
}

// NewUserStoreMock returns a mock for UserStore
func NewUserStoreMock(t minimock.Tester) *UserStoreMock {
	m := &UserStoreMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mUserStoreMockCreate{mock: m}
	m.CreateMock.callArgs = []*UserStoreMockCreateParams{}

	m.GetByEmailMock = mUserStoreMockGetByEmail{mock: m}
	m.GetByEmailMock.callArgs = []*UserStoreMockGetByEmailParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserStoreMockCreate struct {
	optional           bool
	mock               *UserStoreMock
	defaultExpectation *UserStoreMockCreateExpectation
	expectations       []*UserStoreMockCreateExpectation

	callArgs []*UserStoreMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserStoreMockCreateExpectation specifies expectation struct of the UserStore.Create
type UserStoreMockCreateExpectation struct {
	mock               *UserStoreMock
	params             *UserStoreMockCreateParams
	paramPtrs          *UserStoreMockCreateParamPtrs
	expectationOrigins UserStoreMockCreateExpectationOrigins
	results            *UserStoreMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// UserStoreMockCreateParams contains parameters of the UserStore.Create
type UserStoreMockCreateParams struct {
	ctx  context.Context
	user domain.User
}

// UserStoreMockCreateParamPtrs contains pointers to parameters of the UserStore.Create
type UserStoreMockCreateParamPtrs struct {
	ctx  *context.Context
	user *domain.User
}

// UserStoreMockCreateResults contains results of the UserStore.Create
type UserStoreMockCreateResults struct {
	u1  domain.User
	err error
}

// UserStoreMockCreateOrigins contains origins of expectations of the UserStore.Create
type UserStoreMockCreateExpectationOrigins struct {
	origin     string
	originCtx  string
	originUser string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mUserStoreMockCreate) Optional() *mUserStoreMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for UserStore.Create
func (mmCreate *mUserStoreMockCreate) Expect(ctx context.Context, user domain.User) *mUserStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserStoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserStoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("UserStoreMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &UserStoreMockCreateParams{ctx, user}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for UserStore.Create
func (mmCreate *mUserStoreMockCreate) ExpectCtxParam1(ctx context.Context) *mUserStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserStoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserStoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UserStoreMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UserStoreMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectUserParam2 sets up expected param user for UserStore.Create
func (mmCreate *mUserStoreMockCreate) ExpectUserParam2(user domain.User) *mUserStoreMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserStoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserStoreMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("UserStoreMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &UserStoreMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.user = &user
	mmCreate.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the UserStore.Create
func (mmCreate *mUserStoreMockCreate) Inspect(f func(ctx context.Context, user domain.User)) *mUserStoreMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for UserStoreMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by UserStore.Create
func (mmCreate *mUserStoreMockCreate) Return(u1 domain.User, err error) *UserStoreMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserStoreMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &UserStoreMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &UserStoreMockCreateResults{u1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the UserStore.Create method
func (mmCreate *mUserStoreMockCreate) Set(f func(ctx context.Context, user domain.User) (u1 domain.User, err error)) *UserStoreMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the UserStore.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the UserStore.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the UserStore.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mUserStoreMockCreate) When(ctx context.Context, user domain.User) *UserStoreMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("UserStoreMock.Create mock is already set by Set")
	}

	expectation := &UserStoreMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &UserStoreMockCreateParams{ctx, user},
		expectationOrigins: UserStoreMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up UserStore.Create return parameters for the expectation previously defined by the When method
func (e *UserStoreMockCreateExpectation) Then(u1 domain.User, err error) *UserStoreMock {
	e.results = &UserStoreMockCreateResults{u1, err}
	return e.mock
}

// Times sets number of times UserStore.Create should be invoked
func (mmCreate *mUserStoreMockCreate) Times(n uint64) *mUserStoreMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of UserStoreMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mUserStoreMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements UserStore
func (mmCreate *UserStoreMock) Create(ctx context.Context, user domain.User) (u1 domain.User, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, user)
	}

	mm_params := UserStoreMockCreateParams{ctx, user}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := UserStoreMockCreateParams{ctx, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("UserStoreMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmCreate.t.Errorf("UserStoreMock.Create got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("UserStoreMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the UserStoreMock.Create")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, user)
	}
	mmCreate.t.Fatalf("Unexpected call to UserStoreMock.Create. %v %v", ctx, user)
	return
}

// CreateAfterCounter returns a count of finished UserStoreMock.Create invocations
func (mmCreate *UserStoreMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of UserStoreMock.Create invocations
func (mmCreate *UserStoreMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to UserStoreMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mUserStoreMockCreate) Calls() []*UserStoreMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*UserStoreMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *UserStoreMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *UserStoreMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserStoreMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserStoreMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserStoreMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to UserStoreMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to UserStoreMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mUserStoreMockGetByEmail struct {
	optional           bool
	mock               *UserStoreMock
	defaultExpectation *UserStoreMockGetByEmailExpectation
	expectations       []*UserStoreMockGetByEmailExpectation

	callArgs []*UserStoreMockGetByEmailParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserStoreMockGetByEmailExpectation specifies expectation struct of the UserStore.GetByEmail
type UserStoreMockGetByEmailExpectation struct {
	mock               *UserStoreMock
	params             *UserStoreMockGetByEmailParams
	paramPtrs          *UserStoreMockGetByEmailParamPtrs
	expectationOrigins UserStoreMockGetByEmailExpectationOrigins
	results            *UserStoreMockGetByEmailResults
	returnOrigin       string
	Counter            uint64
}

// UserStoreMockGetByEmailParams contains parameters of the UserStore.GetByEmail
type UserStoreMockGetByEmailParams struct {
	ctx   context.Context
	email string
}

// UserStoreMockGetByEmailParamPtrs contains pointers to parameters of the UserStore.GetByEmail
type UserStoreMockGetByEmailParamPtrs struct {
	ctx   *context.Context
	email *string
}

// UserStoreMockGetByEmailResults contains results of the UserStore.GetByEmail
type UserStoreMockGetByEmailResults struct {
	u1  domain.User
	err error
}

// UserStoreMockGetByEmailOrigins contains origins of expectations of the UserStore.GetByEmail
type UserStoreMockGetByEmailExpectationOrigins struct {
	origin      string
	originCtx   string
	originEmail string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByEmail *mUserStoreMockGetByEmail) Optional() *mUserStoreMockGetByEmail {
	mmGetByEmail.optional = true
	return mmGetByEmail
}

// Expect sets up expected params for UserStore.GetByEmail
func (mmGetByEmail *mUserStoreMockGetByEmail) Expect(ctx context.Context, email string) *mUserStoreMockGetByEmail {
	if mmGetByEmail.mock.funcGetByEmail != nil {
		mmGetByEmail.mock.t.Fatalf("UserStoreMock.GetByEmail mock is already set by Set")
	}

	if mmGetByEmail.defaultExpectation == nil {
		mmGetByEmail.defaultExpectation = &UserStoreMockGetByEmailExpectation{}
	}

	if mmGetByEmail.defaultExpectation.paramPtrs != nil {
		mmGetByEmail.mock.t.Fatalf("UserStoreMock.GetByEmail mock is already set by ExpectParams functions")
	}

	mmGetByEmail.defaultExpectation.params = &UserStoreMockGetByEmailParams{ctx, email}
	mmGetByEmail.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByEmail.expectations {
		if minimock.Equal(e.params, mmGetByEmail.defaultExpectation.params) {
			mmGetByEmail.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByEmail.defaultExpectation.params)
		}
	}

	return mmGetByEmail
}

// ExpectCtxParam1 sets up expected param ctx for UserStore.GetByEmail
func (mmGetByEmail *mUserStoreMockGetByEmail) ExpectCtxParam1(ctx context.Context) *mUserStoreMockGetByEmail {
	if mmGetByEmail.mock.funcGetByEmail != nil {
		mmGetByEmail.mock.t.Fatalf("UserStoreMock.GetByEmail mock is already set by Set")
	}

	if mmGetByEmail.defaultExpectation == nil {
		mmGetByEmail.defaultExpectation = &UserStoreMockGetByEmailExpectation{}
	}

	if mmGetByEmail.defaultExpectation.params != nil {
		mmGetByEmail.mock.t.Fatalf("UserStoreMock.GetByEmail mock is already set by Expect")
	}

	if mmGetByEmail.defaultExpectation.paramPtrs == nil {
		mmGetByEmail.defaultExpectation.paramPtrs = &UserStoreMockGetByEmailParamPtrs{}
	}
	mmGetByEmail.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByEmail.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByEmail
}

// ExpectEmailParam2 sets up expected param email for UserStore.GetByEmail
func (mmGetByEmail *mUserStoreMockGetByEmail) ExpectEmailParam2(email string) *mUserStoreMockGetByEmail {
	if mmGetByEmail.mock.funcGetByEmail != nil {
		mmGetByEmail.mock.t.Fatalf("UserStoreMock.GetByEmail mock is already set by Set")
	}

	if mmGetByEmail.defaultExpectation == nil {
		mmGetByEmail.defaultExpectation = &UserStoreMockGetByEmailExpectation{}
	}

	if mmGetByEmail.defaultExpectation.params != nil {
		mmGetByEmail.mock.t.Fatalf("UserStoreMock.GetByEmail mock is already set by Expect")
	}

	if mmGetByEmail.defaultExpectation.paramPtrs == nil {
		mmGetByEmail.defaultExpectation.paramPtrs = &UserStoreMockGetByEmailParamPtrs{}
	}
	mmGetByEmail.defaultExpectation.paramPtrs.email = &email
	mmGetByEmail.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmGetByEmail
}

// Inspect accepts an inspector function that has same arguments as the UserStore.GetByEmail
func (mmGetByEmail *mUserStoreMockGetByEmail) Inspect(f func(ctx context.Context, email string)) *mUserStoreMockGetByEmail {
	if mmGetByEmail.mock.inspectFuncGetByEmail != nil {
		mmGetByEmail.mock.t.Fatalf("Inspect function is already set for UserStoreMock.GetByEmail")
	}

	mmGetByEmail.mock.inspectFuncGetByEmail = f

	return mmGetByEmail
}

// Return sets up results that will be returned by UserStore.GetByEmail
func (mmGetByEmail *mUserStoreMockGetByEmail) Return(u1 domain.User, err error) *UserStoreMock {
	if mmGetByEmail.mock.funcGetByEmail != nil {
		mmGetByEmail.mock.t.Fatalf("UserStoreMock.GetByEmail mock is already set by Set")
	}

	if mmGetByEmail.defaultExpectation == nil {
		mmGetByEmail.defaultExpectation = &UserStoreMockGetByEmailExpectation{mock: mmGetByEmail.mock}
	}
	mmGetByEmail.defaultExpectation.results = &UserStoreMockGetByEmailResults{u1, err}
	mmGetByEmail.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByEmail.mock
}

// Set uses given function f to mock the UserStore.GetByEmail method
func (mmGetByEmail *mUserStoreMockGetByEmail) Set(f func(ctx context.Context, email string) (u1 domain.User, err error)) *UserStoreMock {
	if mmGetByEmail.defaultExpectation != nil {
		mmGetByEmail.mock.t.Fatalf("Default expectation is already set for the UserStore.GetByEmail method")
	}

	if len(mmGetByEmail.expectations) > 0 {
		mmGetByEmail.mock.t.Fatalf("Some expectations are already set for the UserStore.GetByEmail method")
	}

	mmGetByEmail.mock.funcGetByEmail = f
	mmGetByEmail.mock.funcGetByEmailOrigin = minimock.CallerInfo(1)
	return mmGetByEmail.mock
}

// When sets expectation for the UserStore.GetByEmail which will trigger the result defined by the following
// Then helper
func (mmGetByEmail *mUserStoreMockGetByEmail) When(ctx context.Context, email string) *UserStoreMockGetByEmailExpectation {
	if mmGetByEmail.mock.funcGetByEmail != nil {
		mmGetByEmail.mock.t.Fatalf("UserStoreMock.GetByEmail mock is already set by Set")
	}

	expectation := &UserStoreMockGetByEmailExpectation{
		mock:               mmGetByEmail.mock,
		params:             &UserStoreMockGetByEmailParams{ctx, email},
		expectationOrigins: UserStoreMockGetByEmailExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByEmail.expectations = append(mmGetByEmail.expectations, expectation)
	return expectation
}

// Then sets up UserStore.GetByEmail return parameters for the expectation previously defined by the When method
func (e *UserStoreMockGetByEmailExpectation) Then(u1 domain.User, err error) *UserStoreMock {
	e.results = &UserStoreMockGetByEmailResults{u1, err}
	return e.mock
}

// Times sets number of times UserStore.GetByEmail should be invoked
func (mmGetByEmail *mUserStoreMockGetByEmail) Times(n uint64) *mUserStoreMockGetByEmail {
	if n == 0 {
		mmGetByEmail.mock.t.Fatalf("Times of UserStoreMock.GetByEmail mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByEmail.expectedInvocations, n)
	mmGetByEmail.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByEmail
}

func (mmGetByEmail *mUserStoreMockGetByEmail) invocationsDone() bool {
	if len(mmGetByEmail.expectations) == 0 && mmGetByEmail.defaultExpectation == nil && mmGetByEmail.mock.funcGetByEmail == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByEmail.mock.afterGetByEmailCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByEmail.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByEmail implements UserStore
func (mmGetByEmail *UserStoreMock) GetByEmail(ctx context.Context, email string) (u1 domain.User, err error) {
	mm_atomic.AddUint64(&mmGetByEmail.beforeGetByEmailCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByEmail.afterGetByEmailCounter, 1)

	mmGetByEmail.t.Helper()

	if mmGetByEmail.inspectFuncGetByEmail != nil {
		mmGetByEmail.inspectFuncGetByEmail(ctx, email)
	}

	mm_params := UserStoreMockGetByEmailParams{ctx, email}

	// Record call args
	mmGetByEmail.GetByEmailMock.mutex.Lock()
	mmGetByEmail.GetByEmailMock.callArgs = append(mmGetByEmail.GetByEmailMock.callArgs, &mm_params)
	mmGetByEmail.GetByEmailMock.mutex.Unlock()

	for _, e := range mmGetByEmail.GetByEmailMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmGetByEmail.GetByEmailMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByEmail.GetByEmailMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByEmail.GetByEmailMock.defaultExpectation.params
		mm_want_ptrs := mmGetByEmail.GetByEmailMock.defaultExpectation.paramPtrs

		mm_got := UserStoreMockGetByEmailParams{ctx, email}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByEmail.t.Errorf("UserStoreMock.GetByEmail got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByEmail.GetByEmailMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmGetByEmail.t.Errorf("UserStoreMock.GetByEmail got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByEmail.GetByEmailMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByEmail.t.Errorf("UserStoreMock.GetByEmail got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByEmail.GetByEmailMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByEmail.GetByEmailMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByEmail.t.Fatal("No results are set for the UserStoreMock.GetByEmail")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmGetByEmail.funcGetByEmail != nil {
		return mmGetByEmail.funcGetByEmail(ctx, email)
	}
	mmGetByEmail.t.Fatalf("Unexpected call to UserStoreMock.GetByEmail. %v %v", ctx, email)
	return
}

// GetByEmailAfterCounter returns a count of finished UserStoreMock.GetByEmail invocations
func (mmGetByEmail *UserStoreMock) GetByEmailAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByEmail.afterGetByEmailCounter)
}

// GetByEmailBeforeCounter returns a count of UserStoreMock.GetByEmail invocations
func (mmGetByEmail *UserStoreMock) GetByEmailBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByEmail.beforeGetByEmailCounter)
}

// Calls returns a list of arguments used in each call to UserStoreMock.GetByEmail.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByEmail *mUserStoreMockGetByEmail) Calls() []*UserStoreMockGetByEmailParams {
	mmGetByEmail.mutex.RLock()

	argCopy := make([]*UserStoreMockGetByEmailParams, len(mmGetByEmail.callArgs))
	copy(argCopy, mmGetByEmail.callArgs)

	mmGetByEmail.mutex.RUnlock()

	return argCopy
}

// MinimockGetByEmailDone returns true if the count of the GetByEmail invocations corresponds
// the number of defined expectations
func (m *UserStoreMock) MinimockGetByEmailDone() bool {
	if m.GetByEmailMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByEmailMock.invocationsDone()
}

// MinimockGetByEmailInspect logs each unmet expectation
func (m *UserStoreMock) MinimockGetByEmailInspect() {
	for _, e := range m.GetByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserStoreMock.GetByEmail at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByEmailCounter := mm_atomic.LoadUint64(&m.afterGetByEmailCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByEmailMock.defaultExpectation != nil && afterGetByEmailCounter < 1 {
		if m.GetByEmailMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserStoreMock.GetByEmail at\n%s", m.GetByEmailMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserStoreMock.GetByEmail at\n%s with params: %#v", m.GetByEmailMock.defaultExpectation.expectationOrigins.origin, *m.GetByEmailMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByEmail != nil && afterGetByEmailCounter < 1 {
		m.t.Errorf("Expected call to UserStoreMock.GetByEmail at\n%s", m.funcGetByEmailOrigin)
	}

	if !m.GetByEmailMock.invocationsDone() && afterGetByEmailCounter > 0 {
		m.t.Errorf("Expected %d calls to UserStoreMock.GetByEmail at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByEmailMock.expectedInvocations), m.GetByEmailMock.expectedInvocationsOrigin, afterGetByEmailCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserStoreMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockGetByEmailInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserStoreMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserStoreMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockGetByEmailDone()
}
